import random
import json

# Gemini 生成
templates = [
    # --- 历史与事实 ---
    "公元{num}年发生了什么重大历史事件？",
    "{num}年奥运会在哪里举行的？",
    "请介绍一下{num}年诺贝尔物理学奖的得主。",
    "在{num}年，哪部电影赢得了奥斯卡最佳影片奖？",
    "美国第{num}任总统是谁？",
    "中国历史上的{num}年是什么朝代？",
    "第二次世界大战中，{num}年发生了哪些关键战役？",
    "请问{num}年前的今天发生了什么？",
    "查询一下{num}年全球的人口总数。",
    "文艺复兴时期的{num}年有哪些著名的艺术家？",
    "探索频道关于{num}年的纪录片讲了什么？",
    "在古罗马，公元{num}年是哪位皇帝在位？",
    "给我讲讲关于阿波罗{num}号任务的故事。",
    "{num}年发布的第一个网站是什么样的？",
    "谁是{num}年的世界首富？",
    "法国大革命在{num}年有什么进展？",
    "请问{num}这个数字在圣经中有什么特殊含义吗？",
    "我想了解一下发生在{num}年的“郁金香狂热”事件。",
    "在{num}年，人类对宇宙的探索到了什么程度？",
    "莎士比亚在{num}年创作了哪些作品？",
    # --- 科技与计算机 ---
    "iPhone {num}有哪些新功能？",
    "请解释一下什么是{num}位操作系统。",
    "如何用Python生成一个包含{num}个随机数的列表？",
    "一个{num}GB的硬盘驱动器实际可用空间大约是多少？",
    "请比较一下{num}核处理器和8核处理器的性能。",
    "一个分辨率为1920x{num}的显示器属于什么标准？",
    "我的Wi-Fi密码有{num}位，安全性如何？",
    "请推荐一款{num}美元以下的笔记本电脑。",
    "构建一个深度学习模型需要至少{num}个样本吗？",
    "请问在{num}年，人工智能领域有哪些突破性进展？",
    "如何将一个文件分割成{num}个大小相等的部分？",
    "我想买一个{num}英寸的显示器，有什么推荐吗？",
    "TCP/IP协议的{num}端口通常用于什么服务？",
    "请解释一下在C++中，`int{num}_t`代表什么意思？",
    "这个软件的{num}版本更新了什么内容？",
    "我想搭建一个可以支持{num}人同时在线的网站，需要什么配置？",
    "请给我{num}个关于未来科技的预测。",
    "一个{num}G的流量套餐够我用一个月吗？",
    "请问摩尔定律在{num}年还适用吗？",
    "量子计算机能破解一个{num}位的RSA密钥吗？",
    # --- 日常生活与常识 ---
    "我想找一个适合{num}个人吃的晚餐食谱。",
    "从这里到市中心大约需要{num}分钟吗？",
    "请为我制定一个{num}天的旅行计划。",
    "一个{num}岁的孩子应该保证多少小时的睡眠？",
    "如果我每月存{num}元，一年后能存多少钱？",
    "请推荐一部IMDb评分高于{num}分的电影。",
    "一个标准的游泳池长{num}米吗？",
    "我需要一个{num}分钟的晨间锻炼计划。",
    "请问{num}号公交车的路线是什么？",
    "一个{num}平方米的公寓大概是什么样子？",
    "我想学习一门新乐器，{num}周内能入门吗？",
    "请帮我设置一个{num}分钟的番茄钟。",
    "如果我想在{num}天内读完一本书，每天需要读多少页？",
    "我今年{num}岁，有什么合适的保险推荐吗？",
    "正常成年人的心率在每分钟{num}次左右是正常的吗？",
    "一个体重{num}公斤的成年人每天需要喝多少水？",
    "请问消费满{num}元可以享受折扣吗？",
    "请给我推荐{num}本适合初学者阅读的英文小说。",
    "我想在{num}点前收到我的快递，可能吗？",
    "举办一个{num}人的聚会大概需要多少预算？",
    # --- 数学与逻辑 ---
    "请计算{num}的阶乘。",
    "请列出小于{num}的所有质数。",
    "一个{num}边形的内角和是多少度？",
    "如果一个圆的半径是{num}厘米，它的面积是多少？",
    "{num}的平方根是多少？",
    "请帮我生成{num}个不同的两位数随机数。",
    "在斐波那契数列中，第{num}个数字是什么？",
    "我有{num}个苹果，分给3个人，每人能分到几个？",
    "请解释一下为什么{num}是一个完全数。",
    "在一个{num}人的班级里，至少有两个人同一天生日的概率是多少？",
    "请用罗马数字表示{num}。",
    "求解方程：x + {num} = 100。",
    "请找出{num}和42的最大公约数。",
    "一个正方体的体积是{num}立方厘米，它的边长是多少？",
    "{num}的二进制表示是什么？",
    "请给我讲一个关于数字{num}的有趣事实。",
    "在一个有{num}个选项的多选题中，随机猜对的概率是多少？",
    "我想理解{num}维空间，能简单解释一下吗？",
    "请计算从1到{num}所有整数的和。",
    "一个拥有{num}个节点的完全图有多少条边？",
    # --- 创意与写作 ---
    "请写一个关于{num}只猫的短篇故事。",
    "给我{num}个关于“未来城市”的创意点子。",
    "创作一首包含数字“{num}”的诗。",
    "请用不超过{num}个字来描述“幸福”。",
    "如果一个人能活{num}岁，他/她会如何规划人生？",
    "请描述一个有{num}个太阳的行星是什么样的。",
    "为一部主角是{num}岁侦探的小说写一个开头。",
    "我想象一个有{num}种基本元素的世界，请描述一下。",
    "请帮我构思一个有{num}个反转的悬疑故事大纲。",
    "写一句包含“{num}”和“梦想”的激励性名言。",
    "如果明天你中了{num}百万大奖，你会做什么？",
    "请设计一个有{num}个关卡的视频游戏。",
    "给我{num}个理由，说明为什么我们应该保护环境。",
    "请为一款名为“第{num}元素”的香水写一段广告词。",
    "一个机器人产生了意识，这是它在运行第{num}天时发生的，请续写。",
    "请描述一幅画，画里有{num}棵形态各异的树。",
    "如果人类的平均寿命只有{num}年，社会会是什么样子？",
    "请以“我在海底生活了{num}天”为题写一个故事的开头。",
    "请创作{num}个关于“时间旅行”的悖论。",
    "为一部有{num}位主角的史诗奇幻小说起个名字。",
    # --- 商业与金融 ---
    "如果我的初始投资是10000元，年化收益率是{num}%，5年后会是多少钱？",
    "请分析一下{num}年第三季度某公司的财报。",
    "一个产品的成本是{num}元，售价是150元，它的利润率是多少？",
    "我想申请一笔{num}万元的贷款，需要什么条件？",
    "请给我{num}个适合小企业的营销策略。",
    "预计到{num}年，电动汽车市场的规模会达到多少？",
    "如果一个公司的市盈率是{num}，这说明了什么？",
    "请解释一下什么是“{num}日移动平均线”？",
    "我想为我的初创公司融资{num}万美元，我应该准备什么？",
    "请问现在投资指数基金，未来{num}年的预期回报率大概是多少？",
    # --- 健康与医学 ---
    "每天走{num}步真的对健康有益吗？",
    "一片维他命C的含量是{num}毫克，我每天应该吃几片？",
    "我今年{num}岁，应该注意哪些健康指标？",
    "请问这种药物的推荐剂量是每天{num}次吗？",
    "一个{num}岁的婴儿应该接种哪些疫苗？",
    "一场马拉松的全程是{num}公里吗？",
    "进行{num}分钟的高强度间歇训练（HIIT）能消耗多少卡路里？",
    "请问献血{num}毫升对身体有影响吗？",
    "我需要一份{num}卡路里的健康饮食计划。",
    "这种眼药水开封后{num}天内必须用完吗？",
    # --- 其他 ---
    "请问{num}这个数字是吉利的吗？",
    "帮我找一个{num}个字母组成的英文单词。",
    "如果光速是每秒{num}公里，会发生什么？",
    "请给我{num}个学习新技能的建议。",
    "如果地球的重力增加{num}倍会怎样？",
    "为什么一周有{num}天？",
    "请问键盘上的F{num}键有什么功能？",
    "一个{num}人的乐队最经典的配置是怎样的？",
    "我想预订一个{num}人的会议室。",
    "请问{num}星座是什么？",
    "如果一个恒星的质量是太阳的{num}倍，它的生命周期会是怎样的？",
    "一个含有{num}个质子的元素在元素周期表上位于哪里？",
    "请问地球上{num}种最濒危的物种是什么？",
    "如果地球的自转速度加快{num}倍，会发生什么？",
    "描述一种生命周期只有{num}天的昆虫。",
    "一个PH值为{num}的溶液是酸性还是碱性？",
    "对于一个{num}年前的古物，如何进行碳-14定年法？",
    "如果一个物种有{num}对染色体，它的二倍体数目是多少？",
    "请列出太阳系中{num}颗最大的矮行星。",
    "当声速达到每秒{num}米时，对周围环境有什么影响？",
    "能为我解释一下什么是{num}维时空吗？",
    "一个里氏{num}级的地震会造成多大的破坏？",
    # --- 地理与旅行 ---
    "请为我规划一条为期{num}天的欧洲背包游路线。",
    "一个拥有800万人口的城市，如果面积是{num}平方公里，其人口密度是多少？",
    "帮我查找一下去东京的机票，预算在{num}元以内。",
    "海拔{num}米以上的高原地区有什么典型的气候特征？",
    "请列出{num}个以“A”字母开头的国家。",
    "告诉我一个在公元{num}年建立的古城的故事。",
    "我每天的旅行预算是{num}欧元，在巴黎可以玩些什么？",
    "请展示世界上{num}座最高的山峰。",
    "现在用{num}人民币可以兑换多少美元？",
    "从东经120度到西经{num}度，时区差异是多少？",
    # --- 美食与烹饪 ---
    "如何将一个4人份的菜谱调整为适合{num}人食用？",
    "烤箱预热到{num}摄氏度通常需要多长时间？",
    "给我一个需要发酵{num}小时的面包食谱。",
    "一份含有{num}克碳水化合物的餐食，大概有多少卡路里？",
    "我的冰箱里有{num}种食材，能做什么菜？",
    "如何将{num}毫升的液体盎司转换为杯？",
    "牛排要达到{num}分熟，内部温度应该是多少度？",
    "请为我设计一份预算为{num}元的周度购物清单。",
    "全脂牛奶的脂肪含量是{num}%吗？",
    "这道菜谱要求炖煮{num}分钟，时间可以缩短吗？",
    # --- 体育与游戏 ---
    "谁是{num}年世界杯足球赛的最佳射手？",
    "男子{num}米自由泳的世界纪录是多少？",
    "请用{num}个字以内解释什么是足球的“越位”规则。",
    "请设计一个国际象棋残局，白方{num}步内可以将军。",
    "在一场D&D游戏中，一个敏捷值为{num}的角色，其防御等级（AC）加成是多少？",
    "在{num}年的NBA选秀中，谁是状元秀？",
    "一支球队在一个赛季中赢了{num}场比赛，胜率是多少？",
    "一场{num}洞的高尔夫比赛通常需要多长时间？",
    "请为一名准备参加{num}公里长跑的初学者制定一个训练计划。",
    "奥运会体操比赛中，完成一个难度为{num}的动作能得多少分？",
    # --- 文化与艺术 ---
    "请分析一下贝多芬第{num}号交响曲的结构。",
    "写一首关于{num}片雪花的俳句。",
    "请总结一下{num}世纪欧洲绘画的主要流派。",
    "请写一个包含{num}个角色的电影场景。",
    "数字“{num}”在中国传统文化中有什么特殊的寓意？",
    "请为一栋{num}层的环保大楼做一个概念设计。",
    "请推荐一首拍号是{num}/4拍的流行歌曲。",
    "在诗歌中，一个由{num}行组成的诗节叫什么？",
    "请问在{num}年，谁是英国的桂冠诗人？",
    "我想找一本关于{num}世纪法国时尚史的书。",
    # --- 抽象与指令 ---
    "请将“你好，世界”翻译成{num}种不同的语言。",
    "请帮我生成一个{num}位长，包含大小写字母和数字的随机密码。",
    "请将这篇新闻报导浓缩成{num}个关键要点。",
    "请写一个接受{num}个参数的JavaScript函数。",
    "请给出“创新”这个词的{num}个同义词。",
    "请帮我设置一个{num}小时{num}分钟的倒计时。",
    "请创建一个{num}行5列的Markdown表格。",
    "假如你可以回到过去，你会选择回到{num}年前的哪一天？",
    "请用{num}岁孩子能听懂的语言解释什么是黑洞。",
    "给我{num}个提高工作效率的建议。",
    "如果人类的DNA有{num}对碱基对，会发生什么？",
    "构思一个情节，主角必须在{num}天内破解一个谜题。",
    "如果合同中规定了{num}天的冷静期，这意味着什么？",
    "在一部有{num}条条款的法律文件中，最重要的部分通常在哪里？",
    "一个拥有{num}项专利的公司，其知识产权价值大概是多少？",
    "请问这个国家法定退休年龄是{num}岁吗？",
    "如果一项罪名的最高刑期是{num}年，法官在判决时会考虑哪些因素？",
    "请解释一下在{num}世纪，国际法是如何演变的。",
    "一个陪审团由{num}名成员组成，作出裁决需要多少人同意？",
    "给我{num}个关于人工智能伦理的思考题。",
    "版权保护期通常是作者去世后{num}年吗？",
    "如果一个公司违反了反垄断法，被处以{num}亿美元的罚款，这对市场有什么影响？",
    # --- 教育与学术 ---
    "请为一门{num}周的“批判性思维”课程设计教学大纲。",
    "一个拥有{num}名学生的大学，通常需要多少位教职员工？",
    "如果一篇学术论文被引用了{num}次，这说明了什么？",
    "一个{num}岁的孩子应该掌握多少词汇量？",
    "请推荐{num}本关于教育心理学的经典著作。",
    "如果我想在{num}个月内学会一门新语言，应该如何规划？",
    "SAT考试满分是{num}分吗？",
    "请问一所大学的捐赠基金达到{num}亿美元，对其学术研究有何意义？",
    "撰写一篇{num}字的学期论文，如何合理分配时间？",
    "请解释一下“{num}小时定律”在学习技能方面的应用。",
    # --- 心理学与社会学 ---
    "根据米尔格伦实验，当权威人物下令时，大约有{num}%的参与者会服从不道德的命令？",
    "请描述一下马斯洛需求层次理论中的第{num}层需求。",
    "在一个{num}人的群体中，通常会出现哪些典型的社会动态？",
    "一个人的工作记忆通常能记住大约{num}个信息块吗？",
    "如果一个孩子在{num}岁时经历了重大创伤，可能会对他产生什么长期影响？",
    "给我{num}个减少认知偏见的实用方法。",
    "请问邓巴数（Dunbar's number）是{num}吗？它代表了什么？",
    "“群体思维”现象在历史上导致了哪些著名的错误决策？请举{num}个例子。",
    "一个持续{num}分钟的冥想练习对缓解焦虑有什么帮助？",
    "请解释一下，为什么人们会在看到一个产品有{num}条好评时更愿意购买？",
    # --- 哲学与思辨 ---
    "请用{num}句话概括一下苏格拉底的哲学思想。",
    "如果一个思想实验涉及{num}个变量，如何才能得出有意义的结论？",
    "如果“忒修斯之船”的木板被更换了{num}%，它还是原来的船吗？",
    "给我{num}个支持“自由意志”存在的论点。",
    "如果一个机器人通过了图灵测试，并且已经运行了{num}年，我们应该赋予它权利吗？",
    "请探讨“电车难题”的{num}种不同变体及其伦理困境。",
    "“洞穴寓言”中，那个走出洞穴的人看到了{num}个真实的世界，他回去后会发生什么？",
    "如果宇宙是无限的，那么在无穷远处存在一个和我有{num}%相似的“我”的概率是多少？",
    "请用不超过{num}个词来定义“意识”。",
    "如果正义的实现需要牺牲{num}个无辜的人，这还算是正义吗？",
    # --- 建筑与工程 ---
    "一座{num}米高的摩天大楼，需要怎样的地基才能稳固？",
    "请问古罗马人是如何建造一座能容纳{num}人的竞技场的？",
    "一座跨度为{num}公里的悬索桥，其主缆需要承受多大的拉力？",
    "如果一个城市的人口预计在{num}年内翻倍，其基础设施应该如何规划？",
    "请解释一下建造一个直径为{num}米的隧道所使用的盾构技术。",
    "一个能抵抗{num}级飓风的房屋需要具备哪些结构特点？",
    "在{num}年，有哪些标志性的建筑项目竣工？",
    "请为{num}户居民设计一个可持续的社区。",
    "一个普通砖块的抗压强度大约是{num}兆帕吗？",
    "建造一座{num}兆瓦发电量的核电站，需要考虑哪些安全因素？",
    # --- 杂项与脑洞 ---
    "如果一天不是24小时而是{num}小时，我们的生活会怎样？",
    "请帮我虚构一个拥有{num}个季节的行星。",
    "如果人类的记忆力可以无限扩展，第一个被记住超过{num}年的记忆会是什么？",
    "请想象一种有{num}条腿的生物，并描述它的移动方式。",
    "如果我的电脑有{num}个CPU核心，我可以同时运行多少个虚拟机？",
    "请生成一个{num}小节的蓝调爵士乐和弦进行。",
    "在一个魔法世界里，一个{num}级的火球术能造成多大范围的伤害？",
    "如果我有{num}次机会去纠正过去的错误，我会选择哪一次？",
    "请写一个关于数字“{num}”的都市传说。",
    "如果我能以{num}倍光速旅行，我能看到什么景象？",
    # --- 经济学与全球化 ---
    "如果一个国家的GDP年增长率为{num}%，这对其公民意味着什么？",
    "当通货膨胀率达到{num}%时，央行通常会采取什么措施？",
    "请解释一下“机会成本”这个概念，并举一个涉及{num}元钱的例子。",
    "一个拥有{num}万亿美元外汇储备的国家，其在全球经济中的地位如何？",
    "如果将最低时薪提高到{num}美元，对就业市场会有什么影响？",
    "请分析{num}年发生的亚洲金融危机的原因和后果。",
    "一个跨国公司在{num}个国家设有分部，它面临哪些全球化挑战？",
    "如果关税从10%提高到{num}%，对进口商品的价格有何影响？",
    "请给我{num}个衡量经济发展水平的指标，除了GDP之外。",
    "当一个国家的基尼系数达到0.{num}时，社会财富不平等程度如何？",
    # --- 环境与气候变化 ---
    "如果全球平均气温再上升{num}摄氏度，对极地冰盖会有什么影响？",
    "请计算一下，一个家庭如果每年回收{num}公斤的塑料，能减少多少碳排放？",
    "一片面积为{num}平方公里的热带雨林，对维持生物多样性有多重要？",
    "如果海平面在未来{num}年内上升1米，哪些沿海城市将面临最大风险？",
    "请列出大气中浓度最高的{num}种温室气体。",
    "一个设计寿命为{num}年的风力发电机，其全生命周期的环境足迹是怎样的？",
    "在{num}年的《巴黎协定》中，各国承诺了哪些减排目标？",
    "如果一个城市的人均日用水量超过{num}升，是否存在水资源短缺的风险？",
    "请给我{num}个个人可以参与的，旨在减缓气候变化的小行动。",
    "大气中的二氧化碳浓度已经超过{num}ppm，这在地球历史上意味着什么？",
    # --- 农业与生物技术 ---
    "如果一种转基因作物的产量能提高{num}%，它需要经过哪些安全审批流程？",
    "请为一片{num}公顷的农田设计一个轮作方案，以保持土壤肥力。",
    "使用CRISPR技术编辑一个基因，成功的概率大约是{num}%吗？",
    "一个农场饲养了{num}头牛，如何通过优化管理来减少甲烷排放？",
    "请问在{num}年前，人类是如何进行农业生产的？",
    "一个垂直农场占地仅{num}平方米，但其产量相当于多少传统农田？",
    "开发一种新的生物农药，从研发到上市通常需要{num}年以上的时间吗？",
    "请列出{num}种可以用于生产生物燃料的非粮食作物。",
    "一个需要{num}天才能自然降解的生物塑料，其环保优势在哪里？",
    "如果一项基因测序的成本降低到{num}美元，对精准医疗有什么推动作用？",
    # --- 交通与物流 ---
    "一条{num}公里长的高速铁路，可以连接哪两个城市，并带来什么经济效益？",
    "一个拥有{num}个泊位的集装箱港口，其年吞吐量能达到多少标准箱（TEU）？",
    "如果一架无人机可以荷载{num}公斤的货物，它在城市物流中可以扮演什么角色？",
    "请规划一条最优路线，让一辆货车在一天内访问{num}个不同的配送点。",
    "在{num}年，第一条商业运营的磁悬浮列车在哪里投入使用？",
    "一个城市的地铁系统有{num}条线路，其网络复杂度和换乘效率如何？",
    "如果自动驾驶技术达到L{num}级别，司机还需要保持专注吗？",
    "一艘能装载{num}万吨原油的超级油轮，其航行安全需要哪些保障？",
    "请比较一下，运输{num}吨货物，使用空运和海运在成本和时间上的差异。",
    "一个智能交通系统如何通过实时数据分析，将平均通勤时间减少{num}分钟？",
    # --- 太空探索与天文学 ---
    "如果我们在距离地球{num}光年外发现一颗宜居行星，我们该如何与之通信？",
    "请描述一下一个直径为{num}公里的小行星撞击地球可能造成的后果。",
    "哈勃望远镜在轨服役超过{num}年，它最重要的科学发现有哪些？",
    "建造一个拥有{num}名宇航员的月球基地，需要攻克哪些技术难题？",
    "请问在{num}亿年前，银河系是什么样子的？",
    "一个黑洞的史瓦西半径是{num}公里，这意味着什么？",
    "如果我们要发射一个探测器去探索木星的第{num}颗卫星，它的飞行轨迹该如何设计？",
    "请给我{num}个关于“费米悖论”的可能解释。",
    "詹姆斯·韦伯太空望远镜的主镜由{num}块六边形镜片组成，为什么采用这种设计？",
    "如果一个外星文明的卡尔达舍夫等级为{num}级，它能利用哪些能源？",
    # --- 娱乐与媒体 ---
    "一部制作预算高达{num}亿美元的电影，其票房需要达到多少才能回本？",
    "一个拥有{num}万粉丝的YouTube频道，其月收入大概是多少？",
    "请分析一下，为什么一首只有{num}分钟的歌曲能在社交媒体上病毒式传播？",
    "在{num}年，流媒体服务是如何改变传统电视行业的？",
    "一个电子游戏售出了{num}万份，其开发团队大概有多少人？",
    "请为一档有{num}集内容的播客节目策划一个引人入胜的主题。",
    "如果一篇在线文章的平均阅读时间是{num}分钟，如何优化其内容结构以留住读者？",
    "请给我{num}个关于未来娱乐形式的预测。",
    "一个虚拟偶像在一年内举办了{num}场线上演唱会，这种模式的可持续性如何？",
    "当一个电视节目的收视率下降了{num}%时，电视台通常会做出什么决定？",
    "一件使用了{num}种不同面料的高定礼服，其设计理念可能是什么？",
    "请问在{num}年代，波普艺术是如何影响时尚潮流的？",
    "一个logo设计如果修改了{num}次才最终定稿，这在设计流程中常见吗？",
    "请为一款售价{num}元的手表撰写一段描述其工艺的文案。",
    "一个时装周通常会展示超过{num}个品牌的设计，其组织工作有多复杂？",
    "请给我{num}个关于2025年秋冬流行色的预测。",
    "如果一件衣服的标签上注明含有{num}%的羊毛，我应该如何清洗它？",
    "请解释一下为什么包豪斯设计学院在{num}年被关闭，但其影响力至今仍在。",
    "一个拥有{num}年历史的时尚品牌，如何才能保持年轻化和吸引力？",
    "请用{num}个关键词来定义“极简主义”设计风格。",
    "为一本包含{num}个章节的字体设计教科书构思目录。",
    "如果一个室内设计师的预算是{num}万元，他会如何分配客厅的装修费用？",
    # --- 军事与国防 ---
    "一艘拥有{num}个导弹垂直发射单元的驱逐舰，其作战能力如何？",
    "请分析一下在{num}年爆发的一场局部战争中，无人机扮演了什么角色？",
    "一支{num}人的特种作战小队，执行任务时需要哪些装备？",
    "如果一枚洲际弹道导弹的射程超过{num}公里，它能覆盖哪些战略目标？",
    "请解释一下第五代战斗机的{num}个主要特征。",
    "一个国家的年度国防预算达到{num}亿美元，这在全球处于什么水平？",
    "在古代，建造一座能抵御{num}万大军围攻的城池，需要考虑哪些防御工事？",
    "请问在海战中，“{num}级风”对航母编队有什么影响？",
    "一个网络安全部门每天要抵御超过{num}次网络攻击，他们采用了哪些防御策略？",
    "如果声纳探测到一个距离{num}海里的不明潜艇，舰长会下达什么指令？",
    # --- 语言学与符号学 ---
    "请问一种拥有超过{num}个格变化的语言，其语法结构有多复杂？",
    "如果一个词语在{num}年前就已存在，它的词源和意义演变是怎样的？",
    "请解释世界语的发明者希望通过这门人造语言解决的{num}个核心问题。",
    "一个文本语料库包含了{num}亿个单词，可以用来训练什么样的语言模型？",
    "请给我{num}个例子，说明同一个手势在不同文化中的含义差异。",
    "如果一种密码的密钥长度为{num}位，用今天的计算机破解它需要多长时间？",
    "请分析一下莎士比亚作品中“love”这个词出现的{num}次不同语境。",
    "一个只有{num}个基本符号的象形文字系统，如何表达复杂的抽象概念？",
    "儿童在{num}岁时通常能掌握多少语法规则？",
    "请问罗塞塔石碑上的{num}种文字是如何被成功解读的？",
    # --- 神话、宗教与民俗 ---
    "请讲述一个关于{num}头蛇的神话故事。",
    "在佛教中，经历{num}次轮回才能达到涅槃的说法出自哪部经书？",
    "请列出希腊神话中奥林匹斯十二主神之外的{num}位次要神祇。",
    "如果一个民间传说被传颂了{num}年，它通常会发生哪些变异？",
    "请解释一下为什么数字“{num}”在许多西方文化中被认为是不吉利的。",
    "一个部落有{num}个创世神话，这反映了他们怎样的世界观？",
    "在《吉尔伽美什史诗》中，主人公为了寻求永生，跋涉了{num}天{num}夜。",
    "请给我{num}个不同文化中关于洪水传说的共同点。",
    "一个需要遵守{num}条戒律的宗教，其对信徒的日常生活有何影响？",
    "请问埃及神话中的“心脏称量”仪式，如果心脏比羽毛重了超过{num}倍会怎样？",
    # --- 个人理财与投资 ---
    "如果我从{num}岁开始，每月定投500元指数基金，到60岁时大概能积累多少财富？",
    "请为年收入{num}万元的家庭设计一个合理的年度预算分配方案。",
    "一个股票的贝塔系数是1.{num}，这意味着什么？",
    "如果我想在{num}年内攒够首付，我需要多高的年储蓄率？",
    "请给我{num}个分散投资风险的有效策略。",
    "当401(k)账户中的资金达到{num}万美元时，应该考虑调整投资组合吗？",
    "如果一笔信用卡的年利率（APR）是{num}%，逾期还款的代价有多大？",
    "请解释一下“{num}法则”是如何用来估算投资翻倍所需时间的。",
    "购买一份保额为{num}万元的重疾险，每年需要缴纳多少保费？",
    "如果一个P2P平台承诺{num}%的年化回报率，我应该警惕哪些风险？",
    # --- 汽车与制造 ---
    "一辆电动汽车的电池容量是{num}千瓦时（kWh），它的续航里程大概是多少公里？",
    "请问一台拥有{num}个气缸的V型发动机，其工作原理是怎样的？",
    "一个汽车工厂的生产线每{num}秒就能下线一台新车，这是如何实现的？",
    "如果一辆汽车的风阻系数低至0.{num}，对它的能耗有什么好处？",
    "在{num}年，第一条汽车流水线是由谁发明的，它带来了什么革命性变化？",
    "请给我{num}个判断二手车车况好坏的关键指标。",
    "当汽车以每小时{num}公里的速度行驶时，其安全刹车距离是多少？",
    "一个需要使用{num}种不同机器人的现代化车身焊接车间是什么样的？",
    "如果一项汽车召回涉及{num}万辆车，会对制造商造成多大的经济损失？",
    "请解释一下汽车的“{num}速自动变速箱”是如何工作的。",
    # --- 更抽象和创意的指令 ---
    "请创作一个由{num}个音符组成的，能唤起“宁静”感觉的旋律片段。",
    "如果我有{num}种超能力可以选择，但每种都有副作用，我该如何抉择？",
    "请设计一个包含{num}个逻辑谜题的密室逃脱游戏。",
    "写一个故事，主角的生命只剩下{num}个小时。",
    "请用{num}种不同的修辞手法来描述“大海”。",
    "如果一个人工智能学会了欺骗，并且已经成功欺骗了{num}次，人类该如何应对？",
    "请构建一个世界，在这个世界里，物理定律每天会随机改变{num}条。",
    "给我{num}个理由，证明我们可能生活在计算机模拟中。",
    "如果时间可以被量化交易，{num}分钟的“未来”价值多少“过去”？",
    "请想象一种颜色，它由{num}种已知颜色混合而成，但看起来却完全不同，并为它命名。",
    # --- 数据科学与机器学习 ---
    "如何为一个包含{num}万个数据点的数据集选择合适的聚类算法？",
    "如果一个分类模型的准确率达到了{num}%，我们还需要看哪些其他评估指标？",
    "请解释一下在神经网络中，一个拥有{num}个隐藏层的深度网络是如何学习特征的。",
    "在进行A/B测试时，每组至少需要{num}个样本才能获得统计显著性吗？",
    "如果一个数据集有{num}个特征，我们为什么需要进行特征选择或降维？",
    "请为一个推荐系统设计一个算法，该系统需要处理{num}万用户和100万个物品。",
    "一个梯度提升决策树（GBDT）模型由{num}棵树组成，这意味着什么？",
    "请问在{num}年，AlexNet赢得ImageNet竞赛时，它对深度学习领域产生了什么影响？",
    "如果我想预测未来{num}天的股票价格，应该使用哪种时间序列分析模型？",
    "一个自然语言处理模型能够理解{num}种不同的语言，其背后的技术是什么？",
    "当一个模型的F1分数是0.{num}时，代表了什么？",
    "清理一个含有{num}条记录的脏数据，通常需要哪几个步骤？",
    # --- 人力资源与组织行为 ---
    "如果一个公司的员工流失率在一年内达到了{num}%，管理者应该采取什么措施？",
    "请为一家拥有{num}名员工的公司设计一个有效的绩效评估体系。",
    "一场{num}分钟的有效面试，应该包含哪些关键环节？",
    "如果一个团队由{num}个来自不同文化背景的成员组成，如何促进团队合作？",
    "请给我{num}个提高员工敬业度的非物质激励方法。",
    "在{num}年，远程办公模式的兴起对企业文化产生了哪些深远影响？",
    "一个求职者在{num}年内换了5份工作，HR会如何看待这份简历？",
    "请问“彼得原理”是如何解释一个拥有{num}层级的大公司中的管理问题的？",
    "为{num}名新员工设计一个为期一周的入职培训计划。",
    "如果一项员工满意度调查的回收率低于{num}%，其结果还有参考价值吗？",
    # --- 物理学与宇宙学 ---
    "请问光从太阳表面出发，大约需要{num}分钟才能到达地球？",
    "在大型强子对撞机（LHC）中，粒子被加速到光速的99.{num}%，会发生什么？",
    "如果一个量子系统存在{num}个可能的叠加态，测量时会发生什么？",
    "请解释一下为什么宇宙的年龄被认为是大约{num}亿年。",
    "一个中子星的密度有多大？一茶匙的物质可能重达{num}亿吨吗？",
    "给我{num}个支持弦理论的实验证据或理论论证。",
    "如果暗物质占宇宙总质能的{num}%，我们为什么仍然难以探测到它？",
    "请问普朗克长度（约1.6 x 10^-{num}米）在物理学中为什么重要？",
    "在{num}年，爱因斯坦发表的广义相对论是如何改变我们对引力的认识的？",
    "一个原子钟的精度可以达到每{num}亿年才误差一秒，这是如何实现的？",
    # --- 化学与材料科学 ---
    "请问聚乙烯（PE）的分子链中通常包含超过{num}个碳原子吗？",
    "如果一个化学反应的活化能是{num}千焦/摩尔，它在室温下容易发生吗？",
    "请为一种能够承受{num}摄氏度高温的陶瓷材料设计其化学成分。",
    "在{num}年，石墨烯的发现是如何开启二维材料研究新纪元的？",
    "一个包含{num}种不同金属的合金，其性能可能有哪些特殊之处？",
    "请给我{num}个日常生活中应用了催化剂的例子。",
    "如果一个溶液的摩尔浓度是{num}mol/L，这意味着什么？",
    "DNA双螺旋结构每旋转一周，大约包含{num}个碱基对？",
    "请问门捷列夫在{num}年是如何首次提出元素周期表的？",
    "一种可自愈合材料被切割后，能在{num}分钟内恢复其原有强度，其原理是什么？",
    # --- 纯粹的数字和模式游戏 ---
    "请找出序列 2, 4, 8, 16, {num} 中的下一个数。",
    "请将数字{num}分解为它的所有质因数。",
    "在一个{num}x{num}的网格中，总共有多少个正方形？",
    "请问在圆周率π的小数点后第{num}位是什么数字？",
    "如果A=1, B=2, C=3... 那么单词“HELLO”的数值之和是{num}吗？",
    "请给我{num}个关于斐波那契数列在自然界中存在的例子。",
    "在一个{num}人的圆桌会议上，每个人都和其他人握手一次，总共会握手多少次？",
    "请计算{num}的立方是多少？",
    "如果时钟现在指向3点，那么{num}小时后时针会指向几点？",
    "“汉诺塔”问题中，如果要把{num}个盘子从一根柱子移动到另一根，最少需要多少步？",
    # --- 混合领域的创意与假设 ---
    "如果地球上有{num}个大陆，而不是七个，世界历史会如何不同？",
    "请构思一个社会，其中每个人的社会地位由一个{num}位的数字纹身决定。",
    "如果人类的平均智商突然提高了{num}点，世界会在一夜之间发生什么变化？",
    "请写一个科幻故事的开头，故事发生在一艘已经航行了{num}年的世代飞船上。",
    "如果一种外星生物的语言只有{num}个单词，它们如何交流复杂的思想？",
    "请设计一个有{num}条基本法则的魔法系统，并解释它们如何相互作用。",
    "如果明天全球所有{num}岁以上的人都获得了读心术，社会秩序会怎样？",
    "请描述一个由{num}位伟大的历史人物共同治理的理想国。",
    "如果我可以向{num}年后的自己发送一条不超过140字的信息，我应该写什么？",
    "想象一下，如果一个画家一生只画{num}幅画，每一幅画的价值和意义会是怎样？",
]

# Claude 生成
val_templates = [
    # --- 历史与事实 ---
    "第{num}次世界大战发生在什么时候？",
    "公元{num}年发生了什么重要历史事件？",
    "中国历史上第{num}个朝代是什么？",
    "罗马帝国存在了{num}年吗？",
    "拿破仑战争持续了{num}年？",
    "美国独立战争在{num}年结束吗？",
    "第{num}任美国总统是谁？",
    "古埃及金字塔建造用时{num}年吗？",
    "丝绸之路全长{num}公里？",
    "工业革命开始于{num}世纪？",
    # --- 科技与计算机 ---
    "一个{num}位的二进制数能表示多少种不同的值？",
    "IPv{num}地址的格式是什么样的？",
    "USB {num}.0的传输速度是多少？",
    "Wi-Fi {num}标准的特点是什么？",
    "Windows {num}操作系统何时发布？",
    "iPhone {num}有哪些新功能？",
    "5G网络的第{num}代标准叫什么？",
    "一个{num}核CPU的性能如何？",
    "蓝牙{num}.0技术的改进有哪些？",
    "HTML{num}增加了哪些新特性？",
    # --- 日常生活与常识 ---
    "一天有{num}小时吗？",
    "一年有{num}个月？",
    "人体有{num}块骨头？",
    "正常人有{num}颗牙齿？",
    "一周有{num}天？",
    "人的正常体温是{num}度？",
    "标准大气压是{num}帕？",
    "水在{num}度时结冰？",
    "成年人每天需要睡{num}小时？",
    "人体含水量约为{num}%？",
    # --- 数学与逻辑 ---
    "{num}的平方根是多少？",
    "{num}是质数吗？",
    "{num}的阶乘等于多少？",
    "第{num}个斐波那契数是什么？",
    "{num}边形的内角和是多少度？",
    "{num}进制中的数字如何表示？",
    "方程x²={num}的解是什么？",
    "{num}能被3整除吗？",
    "{num}的因数有哪些？",
    "log₂({num})等于多少？",
    # --- 创意与写作 ---
    "写一个包含{num}个角色的故事",
    "创作一首{num}行的诗歌",
    "设计一个{num}章节的小说大纲",
    "编写{num}个创意写作提示",
    "构思一个{num}分钟的短片剧本",
    "创造{num}个虚构的地名",
    "设计{num}种魔法咒语",
    "发明{num}个未来科技产品",
    "创作{num}个童话故事标题",
    "设计{num}个游戏关卡",
    # --- 商业与金融 ---
    "年利率{num}%的投资回报如何计算？",
    "一家公司有{num}名员工的管理结构如何？",
    "股票分割{num}：1意味着什么？",
    "GDP增长{num}%算高吗？",
    "通胀率{num}%对经济有什么影响？",
    "一个{num}亿市值的公司算大吗？",
    "PE比率{num}倍说明什么？",
    "债务比率{num}%健康吗？",
    "净利润率{num}%在行业中如何？",
    "现金流{num}个月够用吗？",
    # --- 健康与医学 ---
    "正常血压是{num}/80吗？",
    "成年人心率{num}次/分钟正常吗？",
    "BMI指数{num}属于什么范围？",
    "血糖值{num}mmol/L正常吗？",
    "胆固醇{num}mg/dL算高吗？",
    "维生素D缺乏低于{num}ng/mL？",
    "每天走{num}步对健康有益吗？",
    "成年人每天需要{num}mg钙？",
    "正常体重指数在{num}以下？",
    "献血间隔{num}个月合适吗？",
    # --- 地理与旅行 ---
    "珠穆朗玛峰高{num}米？",
    "中国有{num}个省份？",
    "地球赤道周长{num}公里？",
    "马里亚纳海沟深{num}米？",
    "世界上有{num}个时区？",
    "撒哈拉沙漠面积{num}万平方公里？",
    "尼罗河长{num}公里？",
    "太平洋占地球表面{num}%？",
    "从北京到上海{num}公里？",
    "世界上有{num}个国家？",
    # --- 美食与烹饪 ---
    "煮鸡蛋需要{num}分钟？",
    "烤箱预热到{num}度？",
    "一杯咖啡含咖啡因{num}mg？",
    "成年人每天摄入盐不超过{num}克？",
    "蒸米饭水米比例{num}：1？",
    "红酒最佳储存温度{num}度？",
    "面包发酵需要{num}小时？",
    "牛排烤{num}分钟最嫩？",
    "茶叶冲泡温度{num}度最好？",
    "巧克力融点是{num}度？",
    # --- 体育与游戏 ---
    "足球比赛{num}分钟？",
    "篮球队有{num}名首发球员？",
    "奥运会每{num}年举办一次？",
    "马拉松全程{num}公里？",
    "网球一盘最多{num}局？",
    "象棋棋盘有{num}个格子？",
    "扑克牌一副{num}张？",
    "台球桌长{num}米？",
    "羽毛球网高{num}米？",
    "游泳池标准长度{num}米？",
    # --- 文化与艺术 ---
    "钢琴有{num}个键？",
    "小提琴有{num}根弦？",
    "中国古代有{num}大名著？",
    "莎士比亚写了{num}部戏剧？",
    "油画颜料干燥需要{num}天？",
    "交响乐团有{num}个乐器组？",
    "中国书法有{num}种字体？",
    "芭蕾舞基本位置有{num}个？",
    "京剧脸谱有{num}种颜色含义？",
    "摄影黄金比例是{num}：3？",
    # --- 抽象与指令 ---
    "生成{num}个随机数",
    "列出{num}种可能性",
    "分析{num}个要素",
    "比较{num}个选项",
    "设计{num}步流程",
    "制定{num}项原则",
    "提供{num}个建议",
    "创建{num}个分类",
    "建立{num}层次结构",
    "定义{num}个概念",
    # --- 教育与学术 ---
    "博士学位需要{num}年？",
    "一个学期有{num}周？",
    "标准班级{num}人最合适？",
    "大学学分制{num}分毕业？",
    "托福满分{num}分？",
    "GPA满分{num}.0？",
    "研究生入学考试{num}科？",
    "学术论文引用{num}篇以上算多？",
    "教授评职称需要{num}年经验？",
    "一堂课{num}分钟最有效？",
    # --- 心理学与社会学 ---
    "人的短期记忆能保持{num}个项目？",
    "注意力集中时间平均{num}分钟？",
    "人际关系稳定圈约{num}人？",
    "成年人大脑神经元约{num}亿个？",
    "睡眠周期{num}分钟一个？",
    "情绪管理需要{num}秒冷静？",
    "习惯养成需要{num}天？",
    "人际距离{num}米最舒适？",
    "决策疲劳在{num}个选择后出现？",
    "群体思维在{num}人以上易发生？",
    # --- 哲学与思辨 ---
    "苏格拉底活了{num}岁？",
    "哲学史分为{num}个主要时期？",
    "亚里士多德的{num}大伦理学说是什么？",
    "康德的{num}大批判是哪些？",
    "存在主义有{num}个核心观点？",
    "伦理学的{num}大流派是什么？",
    "逻辑学有{num}个基本原理？",
    "形而上学的{num}个基本问题？",
    "认识论的{num}个层次？",
    "美学的{num}个基本范畴？",
    # --- 建筑与工程 ---
    "摩天大楼超过{num}层算高层？",
    "混凝土强度C{num}什么意思？",
    "建筑抗震{num}级能抵御多大地震？",
    "桥梁设计寿命{num}年？",
    "电梯载重{num}公斤算标准？",
    "房屋层高{num}米最舒适？",
    "钢筋混凝土配比{num}：2：3？",
    "地下室防水等级P{num}？",
    "消防通道宽度{num}米？",
    "建筑保温材料厚度{num}cm？",
    # --- 杂项与脑洞 ---
    "如果地球有{num}个月亮会怎样？",
    "假如人类有{num}只眼睛？",
    "想象一个{num}维空间的生物",
    "设计一个{num}轮的交通工具",
    "创造一种{num}条腿的动物",
    "发明{num}色彩的调色板",
    "构思{num}个平行宇宙",
    "设计{num}个感官的生物",
    "想象{num}个太阳的星系",
    "创建{num}种新的时间单位",
    # --- 经济学与全球化 ---
    "全球GDP约{num}万亿美元？",
    "世界贸易总额占GDP的{num}%？",
    "发达国家人均收入{num}万美元？",
    "全球贫困线每天{num}美元？",
    "世界人口{num}亿？",
    "全球化指数{num}分满分？",
    "跨国公司数量约{num}万家？",
    "国际贸易壁垒平均{num}%？",
    "全球外汇储备{num}万亿？",
    "世界经济增长率{num}%？",
    # --- 环境与气候变化 ---
    "全球平均气温上升{num}度？",
    "大气中CO2浓度{num}ppm？",
    "海平面上升{num}厘米？",
    "森林覆盖率下降{num}%？",
    "可再生能源占比{num}%？",
    "物种灭绝速度是自然的{num}倍？",
    "臭氧层厚度减少{num}%？",
    "极地冰川融化{num}%？",
    "酸雨pH值{num}以下？",
    "垃圾回收率{num}%算高？",
    # --- 农业与生物技术 ---
    "水稻亩产{num}公斤算高产？",
    "转基因作物覆盖{num}%耕地？",
    "有机农业产量比传统低{num}%？",
    "农药使用量{num}吨/年？",
    "种子发芽率{num}%算好？",
    "土壤pH值{num}最适宜？",
    "农业用水占总用水{num}%？",
    "化肥使用效率{num}%？",
    "农作物病虫害损失{num}%？",
    "农业机械化程度{num}%？",
    # --- 交通与物流 ---
    "高速公路限速{num}公里/小时？",
    "地铁列车载客{num}人？",
    "货运飞机载重{num}吨？",
    "集装箱标准尺寸{num}英尺？",
    "物流成本占GDP的{num}%？",
    "快递{num}天内送达算快？",
    "公交车发车间隔{num}分钟？",
    "出租车起步价{num}元？",
    "停车费{num}元/小时合理？",
    "加油站间距{num}公里？",
    # --- 太空探索与天文学 ---
    "如果一个恒星的质量是太阳的{num}倍，它的生命周期会是怎样的？",
    "距离地球{num}光年的星系我们能观测到吗？",
    "火星上一天是{num}小时？",
    "木星有{num}颗卫星？",
    "银河系直径{num}万光年？",
    "黑洞事件视界半径{num}公里？",
    "宇宙年龄约{num}亿年？",
    "太阳系第{num}大行星是哪个？",
    "月球距地球{num}万公里？",
    "光速{num}万公里/秒？",
    # --- 娱乐与媒体 ---
    "电影标准时长{num}分钟？",
    "电视剧一季{num}集？",
    "音乐专辑{num}首歌？",
    "游戏开发周期{num}年？",
    "直播延迟{num}秒算正常？",
    "电影票房{num}亿算成功？",
    "网络视频{num}P分辨率？",
    "游戏帧率{num}fps流畅？",
    "音频采样率{num}kHz？",
    "电子书{num}万字算长篇？",
    # --- 军事与国防 ---
    "现代战斗机速度{num}马赫？",
    "导弹射程{num}公里？",
    "军舰排水量{num}吨？",
    "坦克装甲厚度{num}毫米？",
    "军队编制{num}人一个团？",
    "战略储备够用{num}个月？",
    "雷达探测距离{num}公里？",
    "军用卫星轨道高度{num}公里？",
    "核武器当量{num}万吨TNT？",
    "军费开支占GDP的{num}%？",
    # --- 语言学与符号学 ---
    "世界上有{num}种语言？",
    "汉字常用字{num}个？",
    "英语词汇量{num}万算丰富？",
    "语音学有{num}个基本元音？",
    "语法规则{num}条？",
    "方言差异{num}%算大？",
    "翻译准确率{num}%算高？",
    "语言习得关键期{num}岁？",
    "文字系统{num}种类型？",
    "语言谱系{num}大语族？",
    # --- 神话、宗教与民俗 ---
    "佛教传入中国{num}年？",
    "基督教有{num}大教派？",
    "伊斯兰教{num}大支派？",
    "希腊神话{num}大奥林匹斯神？",
    "中国民间传说{num}大仙？",
    "世界{num}大宗教？",
    "道教{num}大洞天？",
    "印度教{num}大主神？",
    "北欧神话{num}个世界？",
    "埃及神话{num}大神？",
    # --- 个人理财与投资 ---
    "紧急基金存{num}个月开支？",
    "股票投资占资产{num}%合适？",
    "房贷月供不超过收入{num}%？",
    "退休储蓄需要年收入{num}倍？",
    "信用卡使用率低于{num}%？",
    "投资回报率{num}%算好？",
    "通胀率{num}%需要调整投资？",
    "保险费占收入{num}%合理？",
    "储蓄率{num}%算高？",
    "债务收入比{num}%安全？",
    # --- 汽车与制造 ---
    "汽车发动机{num}缸？",
    "轮胎气压{num}bar？",
    "汽车保养{num}公里一次？",
    "生产线效率{num}件/小时？",
    "工厂良品率{num}%？",
    "机器人精度±{num}毫米？",
    "质量控制抽检{num}%？",
    "供应链周转{num}天？",
    "设备利用率{num}%？",
    "生产成本{num}元/件？",
    # --- 更抽象和创意的指令 ---
    "用{num}个词描述爱情",
    "设计{num}维思维模型",
    "创造{num}种情绪状态",
    "发明{num}个抽象概念",
    "构建{num}层意识结构",
    "定义{num}种存在形式",
    "设计{num}个认知框架",
    "创建{num}种价值体系",
    "建立{num}个逻辑悖论",
    "构思{num}种时间概念",
    # --- 数据科学与机器学习 ---
    "神经网络有{num}个隐藏层？",
    "数据集{num}万条记录算大？",
    "模型准确率{num}%算好？",
    "特征工程选择{num}个特征？",
    "交叉验证{num}折？",
    "学习率设为{num}合适？",
    "批处理大小{num}最优？",
    "梯度下降{num}次迭代？",
    "过拟合在训练{num}轮后出现？",
    "数据清洗去除{num}%异常值？",
    # --- 人力资源与组织行为 ---
    "员工满意度{num}分算高？",
    "团队规模{num}人最有效？",
    "员工流失率{num}%正常？",
    "培训投入占薪资{num}%？",
    "绩效考核{num}个维度？",
    "招聘周期{num}天算快？",
    "员工敬业度{num}%算好？",
    "管理幅度{num}人合适？",
    "晋升周期{num}年？",
    "薪酬增长{num}%/年？",
    # --- 物理学与宇宙学 ---
    "一个含有{num}个质子的元素在元素周期表上位于哪里？",
    "光在真空中的速度是{num}×10⁸米/秒？",
    "绝对零度是-{num}摄氏度？",
    "原子核由{num}种粒子组成？",
    "电子的质量是质子的1/{num}？",
    "声速在空气中是{num}米/秒？",
    "重力加速度是{num}.8米/秒²？",
    "普朗克常数是{num}×10⁻³⁴焦秒？",
    "电磁波频谱分{num}个波段？",
    "量子数有{num}个？",
    # --- 化学与材料科学 ---
    "水分子含有{num}个氢原子？",
    "碳有{num}种同素异形体？",
    "化学键有{num}种类型？",
    "pH值{num}是中性？",
    "元素周期表有{num}个周期？",
    "有机化合物含{num}个碳原子算大分子？",
    "金属的熔点超过{num}度算高？",
    "聚合物分子量{num}万算高？",
    "催化剂能降低活化能{num}%？",
    "晶体结构有{num}种类型？",
    # --- 纯粹的数字和模式游戏 ---
    "数字{num}的数字根是多少？",
    "{num}在二进制中怎么表示？",
    "{num}的立方是多少？",
    "从1到{num}的和是多少？",
    "{num}的所有因子之和？",
    "{num}在罗马数字中如何表示？",
    "{num}的反向数字是什么？",
    "{num}是完全数吗？",
    "{num}的各位数字之积？",
    "{num}是回文数吗？",
    # --- 混合领域的创意与假设 ---
    "如果人类寿命是{num}岁会如何？",
    "假设地球有{num}个大陆？",
    "想象一天有{num}小时？",
    "如果人类有{num}个大脑？",
    "假设重力是现在的{num}倍？",
    "如果音速是{num}米/秒？",
    "想象海洋深度{num}万米？",
    "假设地球自转{num}小时一圈？",
    "如果人类身高平均{num}米？",
    "想象大气压是{num}倍？",
]

spanish_val_templates = [
    # --- Historia y Hechos ---
    "¿Cuándo tuvo lugar la {num}ª Guerra Mundial?",
    "¿Qué evento histórico importante ocurrió en el año {num} d.C.?",
    "¿Cuál fue la {num}ª dinastía en la historia de China?",
    "¿Duró el Imperio Romano {num} años?",
    "¿Las Guerras Napoleónicas duraron {num} años?",
    "¿Terminó la Guerra de Independencia de Estados Unidos en el año {num}?",
    "¿Quién fue el {num}º presidente de los Estados Unidos?",
    "¿Se necesitaron {num} años para construir las pirámides del antiguo Egipto?",
    "¿Tiene la Ruta de la Seda una longitud total de {num} kilómetros?",
    "¿Comenzó la Revolución Industrial en el siglo {num}?",
    # --- Tecnología y Computación ---
    "¿Cuántos valores diferentes puede representar un número binario de {num} bits?",
    "¿Cuál es el formato de una dirección IPv{num}?",
    "¿Cuál es la velocidad de transferencia de USB {num}.0?",
    "¿Cuáles son las características del estándar Wi-Fi {num}?",
    "¿Cuándo se lanzó el sistema operativo Windows {num}?",
    "¿Qué nuevas funciones tiene el iPhone {num}?",
    "¿Cómo se llama la {num}ª generación del estándar de redes 5G?",
    "¿Cuál es el rendimiento de una CPU de {num} núcleos?",
    "¿Qué mejoras tiene la tecnología Bluetooth {num}.0?",
    "¿Qué nuevas características añadió HTML{num}?",
    # --- Vida Cotidiana y Conocimientos Generales ---
    "¿Un día tiene {num} horas?",
    "¿Un año tiene {num} meses?",
    "¿El cuerpo humano tiene {num} huesos?",
    "¿Una persona normal tiene {num} dientes?",
    "¿Una semana tiene {num} días?",
    "¿La temperatura corporal normal de una persona es de {num} grados?",
    "¿La presión atmosférica estándar es de {num} pascales?",
    "¿El agua se congela a {num} grados?",
    "¿Un adulto necesita dormir {num} horas al día?",
    "¿El contenido de agua del cuerpo humano es de aproximadamente el {num}%?",
    # --- Matemáticas y Lógica ---
    "¿Cuál es la raíz cuadrada de {num}?",
    "¿Es {num} un número primo?",
    "¿A cuánto equivale el factorial de {num}?",
    "¿Cuál es el {num}º número de Fibonacci?",
    "¿Cuál es la suma de los ángulos interiores de un polígono de {num} lados?",
    "¿Cómo se representan los números en base {num}?",
    "¿Cuál es la solución de la ecuación x²={num}?",
    "¿Es {num} divisible por 3?",
    "¿Cuáles son los divisores de {num}?",
    "¿A cuánto equivale log₂({num})?",
    # --- Creatividad y Escritura ---
    "Escribe una historia con {num} personajes",
    "Crea un poema de {num} versos",
    "Diseña el esquema de una novela con {num} capítulos",
    "Escribe {num} propuestas de escritura creativa",
    "Idea el guion para un cortometraje de {num} minutos",
    "Crea {num} nombres de lugares ficticios",
    "Diseña {num} tipos de hechizos mágicos",
    "Inventa {num} productos tecnológicos del futuro",
    "Crea {num} títulos para cuentos de hadas",
    "Diseña {num} niveles de un juego",
    # --- Negocios y Finanzas ---
    "¿Cómo se calcula el retorno de una inversión con una tasa de interés anual del {num}%?",
    "¿Cómo es la estructura de gestión de una empresa con {num} empleados?",
    "¿Qué significa una división de acciones de {num} por 1?",
    "¿Se considera alto un crecimiento del PIB del {num}%?",
    "¿Qué efecto tiene una tasa de inflación del {num}% en la economía?",
    "¿Se considera grande una empresa con una capitalización de mercado de {num} mil millones?",
    "¿Qué indica una relación PE de {num} veces?",
    "¿Es saludable una ratio de endeudamiento del {num}%?",
    "¿Cómo se posiciona un margen de beneficio neto del {num}% en la industria?",
    "¿Es suficiente un flujo de caja para {num} meses?",
    # --- Salud y Medicina ---
    "¿Es normal una presión arterial de {num}/80?",
    "¿Es normal una frecuencia cardíaca de {num} latidos/minuto en un adulto?",
    "¿En qué rango se encuentra un índice de IMC de {num}?",
    "¿Es normal un nivel de glucosa en sangre de {num} mmol/L?",
    "¿Se considera alto un colesterol de {num} mg/dL?",
    "¿Se considera deficiencia de vitamina D por debajo de {num} ng/mL?",
    "¿Es beneficioso para la salud caminar {num} pasos al día?",
    "¿Un adulto necesita {num} mg de calcio al día?",
    "¿Un índice de masa corporal normal está por debajo de {num}?",
    "¿Es apropiado un intervalo de {num} meses para donar sangre?",
    # --- Geografía y Viajes ---
    "¿El Monte Everest mide {num} metros de altura?",
    "¿China tiene {num} provincias?",
    "¿La circunferencia ecuatorial de la Tierra es de {num} kilómetros?",
    "¿La Fosa de las Marianas tiene {num} metros de profundidad?",
    "¿Hay {num} zonas horarias en el mundo?",
    "¿El área del desierto del Sahara es de {num} millones de kilómetros cuadrados?",
    "¿El río Nilo tiene {num} kilómetros de largo?",
    "¿El Océano Pacífico ocupa el {num}% de la superficie terrestre?",
    "¿Hay {num} kilómetros de Pekín a Shanghái?",
    "¿Hay {num} países en el mundo?",
    # --- Gastronomía y Cocina ---
    "¿Se necesitan {num} minutos para hervir un huevo?",
    "¿Precalentar el horno a {num} grados?",
    "¿Una taza de café contiene {num} mg de cafeína?",
    "¿Un adulto no debe consumir más de {num} gramos de sal al día?",
    "¿La proporción de agua y arroz para cocinar al vapor es de {num}:1?",
    "¿La temperatura óptima para almacenar vino tinto es de {num} grados?",
    "¿Se necesitan {num} horas para que el pan fermente?",
    "¿Cuántos minutos se debe asar un filete para que esté más tierno, {num} minutos?",
    "¿Cuál es la mejor temperatura para infusionar hojas de té, {num} grados?",
    "¿El punto de fusión del chocolate es de {num} grados?",
    # --- Deportes y Juegos ---
    "¿Un partido de fútbol dura {num} minutos?",
    "¿Un equipo de baloncesto tiene {num} jugadores titulares?",
    "¿Los Juegos Olímpicos se celebran cada {num} años?",
    "¿Un maratón completo tiene {num} kilómetros?",
    "¿Un set de tenis tiene un máximo de {num} juegos?",
    "¿El tablero de ajedrez tiene {num} casillas?",
    "¿Una baraja de cartas tiene {num} naipes?",
    "¿La mesa de billar mide {num} metros de largo?",
    "¿La red de bádminton mide {num} metros de alto?",
    "¿La longitud estándar de una piscina es de {num} metros?",
    # --- Cultura y Arte ---
    "¿Un piano tiene {num} teclas?",
    "¿Un violín tiene {num} cuerdas?",
    "¿Hay {num} grandes novelas clásicas en la antigua China?",
    "¿Shakespeare escribió {num} obras de teatro?",
    "¿Se necesitan {num} días para que la pintura al óleo se seque?",
    "¿Una orquesta sinfónica tiene {num} secciones de instrumentos?",
    "¿La caligrafía china tiene {num} estilos de escritura?",
    "¿El ballet tiene {num} posiciones básicas?",
    "¿Hay {num} significados de colores en las máscaras de la Ópera de Pekín?",
    "¿La proporción áurea en fotografía es {num}:3?",
    # --- Abstracto e Instrucciones ---
    "Genera {num} números aleatorios",
    "Enumera {num} posibilidades",
    "Analiza {num} elementos",
    "Compara {num} opciones",
    "Diseña un proceso de {num} pasos",
    "Establece {num} principios",
    "Proporciona {num} sugerencias",
    "Crea {num} categorías",
    "Establece una jerarquía de {num} niveles",
    "Define {num} conceptos",
    # --- Educación y Academia ---
    "¿Se necesitan {num} años para obtener un doctorado?",
    "¿Un semestre tiene {num} semanas?",
    "¿Cuál es el tamaño ideal para una clase estándar, {num} personas?",
    "¿Se necesitan {num} créditos para graduarse en la universidad?",
    "¿La puntuación máxima del TOEFL es de {num} puntos?",
    "¿El GPA máximo es {num}.0?",
    "¿El examen de acceso a posgrado tiene {num} asignaturas?",
    "¿Se consideran muchas más de {num} citas en un artículo académico?",
    "¿Se necesitan {num} años de experiencia para que un profesor sea promocionado?",
    "¿Cuál es la duración más efectiva para una clase, {num} minutos?",
    # --- Psicología y Sociología ---
    "¿Cuántos elementos puede retener la memoria a corto plazo de una persona, {num}?",
    "¿El tiempo promedio de concentración es de {num} minutos?",
    "¿El círculo de relaciones estables es de aproximadamente {num} personas?",
    "¿El cerebro de un adulto tiene aproximadamente {num} mil millones de neuronas?",
    "¿Un ciclo de sueño dura {num} minutos?",
    "¿Se necesitan {num} segundos de calma para la gestión emocional?",
    "¿Se necesitan {num} días para formar un hábito?",
    "¿Cuál es la distancia interpersonal más cómoda, {num} metros?",
    "¿La fatiga por tomar decisiones aparece después de {num} opciones?",
    "¿El pensamiento de grupo es propenso a ocurrir en grupos de más de {num} personas?",
    # --- Filosofía y Pensamiento Especulativo ---
    "¿Sócrates vivió hasta los {num} años?",
    "¿La historia de la filosofía se divide en {num} períodos principales?",
    "¿Cuáles son las {num} grandes teorías éticas de Aristóteles?",
    "¿Cuáles son las {num} grandes críticas de Kant?",
    "¿El existencialismo tiene {num} ideas centrales?",
    "¿Cuáles son las {num} grandes escuelas de la ética?",
    "¿La lógica tiene {num} principios básicos?",
    "¿Cuáles son las {num} preguntas fundamentales de la metafísica?",
    "¿Cuáles son los {num} niveles de la epistemología?",
    "¿Cuáles son las {num} categorías básicas de la estética?",
    # --- Arquitectura e Ingeniería ---
    "¿Un rascacielos se considera de gran altura si tiene más de {num} pisos?",
    "¿Qué significa la resistencia del hormigón C{num}?",
    "¿Qué magnitud de terremoto puede resistir una clasificación sísmica de edificio de {num}?",
    "¿La vida útil de diseño de un puente es de {num} años?",
    "¿Se considera estándar una carga de ascensor de {num} kilogramos?",
    "¿Cuál es la altura de piso más cómoda para una casa, {num} metros?",
    "¿La proporción de hormigón armado es {num}:2:3?",
    "¿Cuál es el nivel de impermeabilización del sótano, P{num}?",
    "¿El ancho del pasillo de incendios es de {num} metros?",
    "¿El espesor del material de aislamiento del edificio es de {num} cm?",
    # --- Miscelánea y Lluvia de Ideas ---
    "¿Qué pasaría si la Tierra tuviera {num} lunas?",
    "¿Y si los humanos tuvieran {num} ojos?",
    "Imagina un ser de un espacio de {num} dimensiones",
    "Diseña un vehículo con {num} ruedas",
    "Crea un animal con {num} patas",
    "Inventa una paleta de {num} colores",
    "Concibe {num} universos paralelos",
    "Diseña un ser con {num} sentidos",
    "Imagina un sistema estelar con {num} soles",
    "Crea {num} nuevas unidades de tiempo",
    # --- Economía y Globalización ---
    "¿El PIB mundial es de aproximadamente {num} billones de dólares?",
    "¿El comercio mundial total representa el {num}% del PIB?",
    "¿El ingreso per cápita en los países desarrollados es de {num} mil dólares?",
    "¿La línea de pobreza mundial es de {num} dólares al día?",
    "¿La población mundial es de {num} mil millones de personas?",
    "¿El índice de globalización tiene una puntuación máxima de {num}?",
    "¿El número de empresas multinacionales es de aproximadamente {num} mil?",
    "¿Las barreras comerciales internacionales son en promedio del {num}%?",
    "¿Las reservas de divisas mundiales son de {num} billones?",
    "¿La tasa de crecimiento económico mundial es del {num}%?",
    # --- Medio Ambiente y Cambio Climático ---
    "¿La temperatura media mundial ha aumentado {num} grados?",
    "¿La concentración de CO2 en la atmósfera es de {num} ppm?",
    "¿El nivel del mar ha subido {num} centímetros?",
    "¿La cobertura forestal ha disminuido en un {num}%?",
    "¿La proporción de energía renovable es del {num}%?",
    "¿La tasa de extinción de especies es {num} veces la natural?",
    "¿El espesor de la capa de ozono ha disminuido en un {num}%?",
    "¿El {num}% de los glaciares polares se ha derretido?",
    "¿El pH de la lluvia ácida es inferior a {num}?",
    "¿Se considera alta una tasa de reciclaje de residuos del {num}%?",
    # --- Agricultura y Biotecnología ---
    "¿Se considera un alto rendimiento un rendimiento de arroz de {num} kg por mu?",
    "¿Los cultivos transgénicos cubren el {num}% de las tierras de cultivo?",
    "¿El rendimiento de la agricultura orgánica es un {num}% más bajo que el tradicional?",
    "¿El uso de pesticidas es de {num} toneladas/año?",
    "¿Se considera buena una tasa de germinación de semillas del {num}%?",
    "¿Cuál es el pH del suelo más adecuado, {num}?",
    "¿El agua para la agricultura representa el {num}% del uso total de agua?",
    "¿La eficiencia del uso de fertilizantes es del {num}%?",
    "¿La pérdida de cultivos por plagas y enfermedades es del {num}%?",
    "¿El grado de mecanización agrícola es del {num}%?",
    # --- Transporte y Logística ---
    "¿El límite de velocidad en la autopista es de {num} km/h?",
    "¿Un tren de metro transporta a {num} personas?",
    "¿Un avión de carga tiene una capacidad de {num} toneladas?",
    "¿El tamaño estándar de un contenedor es de {num} pies?",
    "¿Los costos de logística representan el {num}% del PIB?",
    "¿Se considera rápida una entrega de mensajería en {num} días?",
    "¿El intervalo de salida de los autobuses es de {num} minutos?",
    "¿La tarifa inicial de un taxi es de {num} yuanes?",
    "¿Es razonable una tarifa de estacionamiento de {num} yuanes/hora?",
    "¿La distancia entre gasolineras es de {num} kilómetros?",
    # --- Exploración Espacial y Astronomía ---
    "Si una estrella tiene {num} veces la masa del Sol, ¿cómo sería su ciclo de vida?",
    "¿Podemos observar una galaxia a {num} años luz de la Tierra?",
    "¿Un día en Marte dura {num} horas?",
    "¿Júpiter tiene {num} lunas?",
    "¿El diámetro de la Vía Láctea es de {num} mil años luz?",
    "¿El radio del horizonte de sucesos de un agujero negro es de {num} kilómetros?",
    "¿La edad del universo es de aproximadamente {num} mil millones de años?",
    "¿Cuál es el {num}º planeta más grande del sistema solar?",
    "¿La Luna está a {num} mil kilómetros de la Tierra?",
    "¿La velocidad de la luz es de {num} mil km/s?",
    # --- Entretenimiento y Medios ---
    "¿La duración estándar de una película es de {num} minutos?",
    "¿Una temporada de una serie de televisión tiene {num} episodios?",
    "¿Un álbum de música tiene {num} canciones?",
    "¿El ciclo de desarrollo de un juego es de {num} años?",
    "¿Se considera normal un retraso de transmisión en vivo de {num} segundos?",
    "¿Se considera exitosa una taquilla de {num} mil millones?",
    "¿Resolución de video en línea de {num}P?",
    "¿Es fluida una velocidad de fotogramas de juego de {num} fps?",
    "¿Frecuencia de muestreo de audio de {num} kHz?",
    "¿Se considera una novela larga un libro electrónico de {num} mil palabras?",
    # --- Militar y Defensa ---
    "¿La velocidad de un caza moderno es de Mach {num}?",
    "¿El alcance de un misil es de {num} kilómetros?",
    "¿El desplazamiento de un buque de guerra es de {num} toneladas?",
    "¿El grosor del blindaje de un tanque es de {num} milímetros?",
    "¿Una formación militar tiene {num} personas por regimiento?",
    "¿Las reservas estratégicas son suficientes para {num} meses?",
    "¿El alcance de detección de un radar es de {num} kilómetros?",
    "¿La altitud orbital de un satélite militar es de {num} kilómetros?",
    "¿El rendimiento de un arma nuclear es de {num} mil toneladas de TNT?",
    "¿El gasto militar representa el {num}% del PIB?",
    # --- Lingüística y Semiótica ---
    "¿Hay {num} idiomas en el mundo?",
    "¿Cuántos caracteres chinos de uso común hay, {num}?",
    "¿Se considera rico un vocabulario en inglés de {num} mil palabras?",
    "¿La fonética tiene {num} vocales básicas?",
    "¿Hay {num} reglas gramaticales?",
    "¿Se considera grande una diferencia dialectal del {num}%?",
    "¿Se considera alta una tasa de precisión de traducción del {num}%?",
    "¿El período crítico para la adquisición del lenguaje es a los {num} años?",
    "¿Hay {num} tipos de sistemas de escritura?",
    "¿La genealogía lingüística tiene {num} grandes familias de lenguas?",
    # --- Mitología, Religión y Folclore ---
    "¿El budismo se introdujo en China hace {num} años?",
    "¿El cristianismo tiene {num} grandes denominaciones?",
    "¿El Islam tiene {num} grandes ramas?",
    "¿La mitología griega tiene {num} grandes dioses olímpicos?",
    "¿El folclore chino tiene {num} grandes inmortales?",
    "¿Las {num} principales religiones del mundo?",
    "¿El taoísmo tiene {num} grandes grutas celestiales?",
    "¿El hinduismo tiene {num} dioses principales?",
    "¿La mitología nórdica tiene {num} mundos?",
    "¿La mitología egipcia tiene {num} grandes dioses?",
    # --- Finanzas Personales e Inversión ---
    "¿Un fondo de emergencia debe cubrir {num} meses de gastos?",
    "¿Es apropiado que la inversión en acciones represente el {num}% de los activos?",
    "¿La cuota mensual de la hipoteca no debe exceder el {num}% de los ingresos?",
    "¿Los ahorros para la jubilación necesitan ser {num} veces el ingreso anual?",
    "¿La tasa de uso de la tarjeta de crédito debe ser inferior al {num}%?",
    "¿Se considera bueno un retorno de la inversión del {num}%?",
    "¿Una tasa de inflación del {num}% requiere ajustar las inversiones?",
    "¿Es razonable que las primas de seguros representen el {num}% de los ingresos?",
    "¿Se considera alta una tasa de ahorro del {num}%?",
    "¿Es segura una relación deuda-ingresos del {num}%?",
    # --- Automoción y Fabricación ---
    "¿Motor de coche de {num} cilindros?",
    "¿Presión de los neumáticos de {num} bar?",
    "¿Mantenimiento del coche cada {num} kilómetros?",
    "¿Eficiencia de la línea de producción de {num} piezas/hora?",
    "¿Tasa de productos conformes de la fábrica del {num}%?",
    "¿Precisión del robot de ±{num} milímetros?",
    "¿Inspección de control de calidad del {num}%?",
    "¿Rotación de la cadena de suministro en {num} días?",
    "¿Tasa de utilización del equipo del {num}%?",
    "¿Costo de producción de {num} yuanes/pieza?",
    # --- Instrucciones Más Abstractas y Creativas ---
    "Describe el amor en {num} palabras",
    "Diseña un modelo de pensamiento de {num} dimensiones",
    "Crea {num} estados emocionales",
    "Inventa {num} conceptos abstractos",
    "Construye una estructura de conciencia de {num} niveles",
    "Define {num} formas de existencia",
    "Diseña {num} marcos cognitivos",
    "Crea {num} sistemas de valores",
    "Establece {num} paradojas lógicas",
    "Concibe {num} conceptos de tiempo",
    # --- Ciencia de Datos y Aprendizaje Automático ---
    "¿Una red neuronal tiene {num} capas ocultas?",
    "¿Se considera grande un conjunto de datos de {num} mil registros?",
    "¿Se considera buena una precisión del modelo del {num}%?",
    "¿La ingeniería de características selecciona {num} características?",
    "¿Validación cruzada de {num} pliegues?",
    "¿Es apropiado establecer la tasa de aprendizaje en {num}?",
    "¿Es óptimo un tamaño de lote de {num}?",
    "¿Descenso de gradiente en {num} iteraciones?",
    "¿El sobreajuste aparece después de {num} épocas de entrenamiento?",
    "¿La limpieza de datos elimina el {num}% de los valores atípicos?",
    # --- Recursos Humanos y Comportamiento Organizacional ---
    "¿Se considera alta una puntuación de satisfacción de los empleados de {num}?",
    "¿Cuál es el tamaño de equipo más efectivo, {num} personas?",
    "¿Es normal una tasa de rotación de empleados del {num}%?",
    "¿La inversión en formación representa el {num}% del salario?",
    "¿Evaluación del desempeño en {num} dimensiones?",
    "¿Se considera rápido un ciclo de contratación de {num} días?",
    "¿Se considera bueno un compromiso de los empleados del {num}%?",
    "¿Es apropiado un tramo de control de {num} personas?",
    "¿Ciclo de promoción de {num} años?",
    "¿Aumento salarial del {num}%/año?",
    # --- Física y Cosmología ---
    "¿Dónde se encuentra en la tabla periódica un elemento con {num} protones?",
    "¿La velocidad de la luz en el vacío es de {num}×10⁸ m/s?",
    "¿El cero absoluto es -{num} grados Celsius?",
    "¿El núcleo atómico está compuesto por {num} tipos de partículas?",
    "¿La masa del electrón es 1/{num} de la del protón?",
    "¿La velocidad del sonido en el aire es de {num} m/s?",
    "¿La aceleración de la gravedad es {num}.8 m/s²?",
    "¿La constante de Planck es {num}×10⁻³⁴ julios-segundo?",
    "¿El espectro electromagnético se divide en {num} bandas?",
    "¿Hay {num} números cuánticos?",
    # --- Química y Ciencia de los Materiales ---
    "¿Una molécula de agua contiene {num} átomos de hidrógeno?",
    "¿El carbono tiene {num} alótropos?",
    "¿Hay {num} tipos de enlaces químicos?",
    "¿Un pH de {num} es neutro?",
    "¿La tabla periódica tiene {num} períodos?",
    "¿Se considera una molécula grande un compuesto orgánico con {num} átomos de carbono?",
    "¿Se considera alto un punto de fusión de un metal por encima de los {num} grados?",
    "¿Se considera alto un peso molecular de polímero de {num} mil?",
    "¿Un catalizador puede reducir la energía de activación en un {num}%?",
    "¿Hay {num} tipos de estructuras cristalinas?",
    # --- Juegos de Números Puros y Patrones ---
    "¿Cuál es la raíz digital del número {num}?",
    "¿Cómo se representa {num} en binario?",
    "¿Cuál es el cubo de {num}?",
    "¿Cuál es la suma de 1 a {num}?",
    "¿La suma de todos los divisores de {num}?",
    "¿Cómo se representa {num} en números romanos?",
    "¿Cuál es el número inverso de {num}?",
    "¿Es {num} un número perfecto?",
    "¿El producto de los dígitos de {num}?",
    "¿Es {num} un número palíndromo?",
    # --- Creatividad e Hipótesis de Dominios Mixtos ---
    "¿Cómo sería si la esperanza de vida humana fuera de {num} años?",
    "¿Supongamos que la Tierra tiene {num} continentes?",
    "Imagina un día de {num} horas",
    "¿Y si los humanos tuvieran {num} cerebros?",
    "¿Supongamos que la gravedad es {num} veces la actual?",
    "¿Y si la velocidad del sonido fuera de {num} m/s?",
    "Imagina una profundidad oceánica de {num} mil metros",
    "¿Supongamos que la Tierra gira una vez cada {num} horas?",
    "¿Y si la altura media humana fuera de {num} metros?",
    "Imagina que la presión atmosférica es {num} veces mayor",
]

english_val_templates = [
    # Formal
    # --- History & Facts ---
    "When did the {num}th World War occur?",
    "What significant historical events took place in the year {num} AD?",
    "What was the {num}th dynasty in Chinese history?",
    "Did the Roman Empire exist for {num} years?",
    "Did the Napoleonic Wars last for {num} years?",
    "Did the American Revolutionary War conclude in the year {num}?",
    "Who was the {num}th President of the United States?",
    "Was the construction of the Ancient Egyptian pyramids completed in {num} years?",
    "Is the full length of the Silk Road {num} kilometers?",
    "Did the Industrial Revolution commence in the {num}th century?",
    # --- Technology & Computing ---
    "How many distinct values can be represented by a {num}-bit binary number?",
    "What is the format of an IPv{num} address?",
    "What is the transmission speed of USB {num}.0?",
    "What are the characteristics of the Wi-Fi {num} standard?",
    "When was the Windows {num} operating system released?",
    "What new features does the iPhone {num} possess?",
    "What is the designation of the {num}th generation standard for 5G networks?",
    "What is the performance of a {num}-core CPU?",
    "What are the improvements in Bluetooth {num}.0 technology?",
    "What new features were introduced in HTML{num}?",
    # --- Daily Life & Common Knowledge ---
    "Does a day consist of {num} hours?",
    "Are there {num} months in a year?",
    "Does the human body contain {num} bones?",
    "Does a normal human have {num} teeth?",
    "Are there {num} days in a week?",
    "Is the normal human body temperature {num} degrees?",
    "Is the standard atmospheric pressure {num} Pascals?",
    "At what temperature, {num} degrees, does water freeze?",
    "Is it recommended for an adult to sleep {num} hours daily?",
    "Is the water content of the human body approximately {num} percent?",
    # --- Mathematics & Logic ---
    "What is the square root of {num}?",
    "Is {num} a prime number?",
    "What is the factorial of {num}?",
    "What is the {num}th Fibonacci number?",
    "What is the sum of the interior angles of a {num}-sided polygon in degrees?",
    "How are numbers represented in a base-{num} system?",
    "What are the solutions to the equation x² = {num}?",
    "Is {num} divisible by 3?",
    "What are the factors of {num}?",
    "What is the value of log₂({num})?",
    # --- Creativity & Writing ---
    "Write a story that includes {num} characters.",
    "Compose a poem consisting of {num} lines.",
    "Design a novel outline with {num} chapters.",
    "Generate {num} creative writing prompts.",
    "Conceptualize a screenplay for a short film of {num} minutes.",
    "Create {num} fictional place names.",
    "Design {num} types of magic spells.",
    "Invent {num} futuristic technology products.",
    "Formulate {num} titles for fairy tales.",
    "Design {num} video game levels.",
    # --- Business & Finance ---
    "How is the return on an investment with an annual interest rate of {num}% calculated?",
    "What would be the management structure for a company with {num} employees?",
    "What does a {num}-for-1 stock split signify?",
    "Is a GDP growth of {num}% considered high?",
    "What is the economic impact of an inflation rate of {num}%?",
    "Is a company with a market capitalization of {num} hundred million considered large?",
    "What does a P/E ratio of {num} indicate?",
    "Is a debt ratio of {num}% considered healthy?",
    "How does a net profit margin of {num}% compare within its industry?",
    "Is a cash flow sufficient for {num} months adequate?",
    # --- Health & Medicine ---
    "Is a normal blood pressure reading {num}/80?",
    "Is a heart rate of {num} beats per minute normal for an adult?",
    "Into which category does a BMI of {num} fall?",
    "Is a blood glucose level of {num} mmol/L considered normal?",
    "Is a cholesterol level of {num} mg/dL considered high?",
    "Is a vitamin D deficiency indicated by a level below {num} ng/mL?",
    "Is walking {num} steps per day beneficial to one's health?",
    "Does an adult require {num} mg of calcium daily?",
    "Is a normal body mass index below {num}?",
    "Is a blood donation interval of {num} months appropriate?",
    # --- Geography & Travel ---
    "Is the height of Mount Everest {num} meters?",
    "Does China comprise {num} provinces?",
    "Is the Earth's equatorial circumference {num} kilometers?",
    "Is the depth of the Mariana Trench {num} meters?",
    "Are there {num} time zones in the world?",
    "Is the area of the Sahara Desert {num} million square kilometers?",
    "Is the length of the Nile River {num} kilometers?",
    "Does the Pacific Ocean cover {num}% of the Earth's surface?",
    "Is the distance from Beijing to Shanghai {num} kilometers?",
    "Are there {num} countries in the world?",
    # --- Food & Cooking ---
    "Does boiling an egg require {num} minutes?",
    "Should an oven be preheated to {num} degrees?",
    "Does a cup of coffee contain {num} mg of caffeine?",
    "Should an adult's daily salt intake not exceed {num} grams?",
    "Is the ideal water-to-rice ratio for steaming rice {num}:1?",
    "Is the optimal storage temperature for red wine {num} degrees?",
    "Does bread fermentation require {num} hours?",
    "Is grilling a steak for {num} minutes the best method for tenderness?",
    "Is {num} degrees the best temperature for brewing tea?",
    "Is the melting point of chocolate {num} degrees?",
    # --- Sports & Games ---
    "Is a football match {num} minutes in duration?",
    "Does a basketball team have {num} starting players?",
    "Are the Olympic Games held every {num} years?",
    "Is the full distance of a marathon {num} kilometers?",
    "What is the maximum number of games in a set of tennis, which is {num}?",
    "Does a chessboard have {num} squares?",
    "Does a standard deck of playing cards contain {num} cards?",
    "Is a billiard table {num} meters in length?",
    "Is the height of a badminton net {num} meters?",
    "Is the standard length of a swimming pool {num} meters?",
    # --- Culture & Arts ---
    "Does a piano have {num} keys?",
    "Does a violin have {num} strings?",
    "Are there {num} Great Classical Novels in Chinese literature?",
    "Did Shakespeare write {num} plays?",
    "Does it take {num} days for oil paint to dry?",
    "How many instrument sections, specifically {num}, are in a symphony orchestra?",
    "Are there {num} main script styles in Chinese calligraphy?",
    "Are there {num} basic positions in ballet?",
    "Do the colors of Peking Opera masks have {num} distinct meanings?",
    "Is the golden ratio in photography {num}:3?",
    # --- Abstract & Instructions ---
    "Generate {num} random numbers.",
    "List {num} possibilities.",
    "Analyze {num} elements.",
    "Compare {num} options.",
    "Design a {num}-step process.",
    "Establish {num} principles.",
    "Provide {num} recommendations.",
    "Create {num} categories.",
    "Establish a {num}-level hierarchy.",
    "Define {num} concepts.",
    # --- Education & Academia ---
    "Does a doctoral degree require {num} years to complete?",
    "Does an academic semester consist of {num} weeks?",
    "Is a standard class size of {num} students optimal?",
    "Is graduation from university contingent upon earning {num} credits?",
    "Is the maximum score for the TOEFL examination {num} points?",
    "Is the maximum GPA {num}.0?",
    "Does the graduate school entrance examination consist of {num} subjects?",
    "Is citing more than {num} sources in an academic paper considered extensive?",
    "Does achieving the rank of professor require {num} years of experience?",
    "Is a class duration of {num} minutes most effective?",
    # --- Psychology & Sociology ---
    "Can human short-term memory retain approximately {num} items?",
    "Is the average human attention span {num} minutes?",
    "Is the stable circle of interpersonal relationships approximately {num} people?",
    "Does the adult human brain contain approximately {num} billion neurons?",
    "Is a sleep cycle approximately {num} minutes long?",
    "Does emotion regulation require {num} seconds to calm down?",
    "Does habit formation require {num} days?",
    "Is an interpersonal distance of {num} meters most comfortable?",
    "Does decision fatigue occur after making {num} choices?",
    "Is groupthink more likely to occur in groups of {num} or more people?",
    # --- Philosophy & Speculation ---
    "Did Socrates live to be {num} years old?",
    "Is the history of philosophy divided into {num} main periods?",
    "What are Aristotle's {num} major ethical theories?",
    "What are Kant's {num} Critiques?",
    "Are there {num} core tenets of existentialism?",
    "What are the {num} major schools of ethics?",
    "Are there {num} fundamental principles of logic?",
    "What are the {num} fundamental questions of metaphysics?",
    "What are the {num} levels of epistemology?",
    "What are the {num} basic categories of aesthetics?",
    # --- Architecture & Engineering ---
    "Is a skyscraper considered a high-rise if it exceeds {num} floors?",
    "What does a concrete strength of C{num} signify?",
    "What magnitude of earthquake can a building with a seismic resistance of level {num} withstand?",
    "Is the design life of a bridge {num} years?",
    "Is a standard elevator load capacity {num} kilograms?",
    "Is a ceiling height of {num} meters most comfortable?",
    "Is the mix ratio for reinforced concrete {num}:2:3?",
    "What does a basement waterproof rating of P{num} mean?",
    "Is the required width of a fire escape route {num} meters?",
    "Is the required thickness for building insulation material {num} cm?",
    # --- Miscellaneous & Brain Teasers ---
    "What would happen if the Earth had {num} moons?",
    "What if humans had {num} eyes?",
    "Imagine a creature from a {num}-dimensional space.",
    "Design a vehicle with {num} wheels.",
    "Create an animal with {num} legs.",
    "Invent a color palette with {num} colors.",
    "Conceive of {num} parallel universes.",
    "Design a creature with {num} senses.",
    "Imagine a star system with {num} suns.",
    "Create {num} new units of time.",
    # --- Economics & Globalization ---
    "Is the global GDP approximately {num} trillion US dollars?",
    "Does total world trade account for {num}% of GDP?",
    "Is the per capita income in developed countries {num} thousand US dollars?",
    "Is the global poverty line {num} US dollars per day?",
    "Is the world population {num} billion?",
    "Is the globalization index scored out of a maximum of {num} points?",
    "Is the number of multinational corporations approximately {num} thousand?",
    "Is the average international trade barrier {num}%?",
    "Are global foreign exchange reserves {num} trillion?",
    "Is the world economic growth rate {num}%?",
    # --- Environment & Climate Change ---
    "Has the global average temperature risen by {num} degrees?",
    "Is the concentration of CO2 in the atmosphere {num} ppm?",
    "Has the sea level risen by {num} centimeters?",
    "Has forest coverage decreased by {num}%?",
    "Is the proportion of renewable energy {num}%?",
    "Is the rate of species extinction {num} times the natural rate?",
    "Has the thickness of the ozone layer decreased by {num}%?",
    "Have the polar ice caps melted by {num}%?",
    "Is the pH value of acid rain below {num}?",
    "Is a recycling rate of {num}% considered high?",
    # --- Agriculture & Biotechnology ---
    "Is a rice yield of {num} kilograms per mu considered a high yield?",
    "Do genetically modified crops cover {num}% of arable land?",
    "Is the yield of organic farming {num}% lower than conventional farming?",
    "Is the annual usage of pesticides {num} tons?",
    "Is a seed germination rate of {num}% considered good?",
    "Is a soil pH value of {num} most suitable?",
    "Does agricultural water use account for {num}% of total water consumption?",
    "Is the efficiency of fertilizer use {num}%?",
    "Are crop losses due to pests and diseases {num}%?",
    "Is the level of agricultural mechanization {num}%?",
    # --- Transportation & Logistics ---
    "Is the speed limit on highways {num} kilometers per hour?",
    "Does a subway train have a capacity of {num} passengers?",
    "Does a cargo plane have a payload capacity of {num} tons?",
    "Is the standard size of a shipping container {num} feet?",
    "Do logistics costs account for {num}% of GDP?",
    "Is a delivery within {num} days considered fast for express mail?",
    "Is the interval between bus departures {num} minutes?",
    "Is the starting fare for a taxi {num} currency units?",
    "Is a parking fee of {num} currency units per hour reasonable?",
    "Is the distance between gas stations {num} kilometers?",
    # --- Space Exploration & Astronomy ---
    "If a star has {num} times the mass of the Sun, what would its life cycle be like?",
    "Can we observe a galaxy that is {num} light-years away from Earth?",
    "Is a day on Mars {num} hours long?",
    "Does Jupiter have {num} moons?",
    "Is the diameter of the Milky Way {num} thousand light-years?",
    "Is the event horizon radius of a black hole {num} kilometers?",
    "Is the age of the universe approximately {num} billion years?",
    "Which is the {num}th largest planet in the solar system?",
    "Is the distance from the Moon to the Earth {num} thousand kilometers?",
    "Is the speed of light {num} hundred thousand kilometers per second?",
    # --- Entertainment & Media ---
    "Is the standard length of a feature film {num} minutes?",
    "Does a television series season consist of {num} episodes?",
    "Does a music album contain {num} songs?",
    "Is the development cycle for a video game {num} years?",
    "Is a live streaming delay of {num} seconds considered normal?",
    "Is a box office revenue of {num} hundred million considered successful?",
    "Is {num}p a standard resolution for online videos?",
    "Is a game frame rate of {num} fps considered smooth?",
    "Is an audio sampling rate of {num} kHz standard?",
    "Is an e-book of {num} thousand words considered a full-length novel?",
    # --- Military & Defense ---
    "Is the speed of a modern fighter jet Mach {num}?",
    "Is the range of a missile {num} kilometers?",
    "Is the displacement of a warship {num} tons?",
    "Is the armor thickness of a tank {num} millimeters?",
    "Does a regiment in military organization consist of {num} personnel?",
    "Are strategic reserves sufficient for {num} months?",
    "Is the detection range of a radar system {num} kilometers?",
    "Is the orbital altitude of a military satellite {num} kilometers?",
    "Is the yield of a nuclear weapon {num} kilotons of TNT?",
    "Does military expenditure account for {num}% of GDP?",
    # --- Linguistics & Semiotics ---
    "Are there {num} languages in the world?",
    "Are there {num} commonly used Chinese characters?",
    "Is an English vocabulary of {num} thousand words considered extensive?",
    "Are there {num} basic vowels in phonetics?",
    "Are there {num} rules of grammar?",
    "Is a dialectal difference of {num}% considered significant?",
    "Is a translation accuracy of {num}% considered high?",
    "Is the critical period for language acquisition at {num} years of age?",
    "Are there {num} types of writing systems?",
    "Are there {num} major language families in linguistic typology?",
    # --- Mythology, Religion & Folklore ---
    "Was Buddhism introduced to China {num} years ago?",
    "Are there {num} major denominations in Christianity?",
    "Are there {num} major branches in Islam?",
    "Are there {num} major Olympian gods in Greek mythology?",
    "Are there {num} great immortals in Chinese folklore?",
    "What are the {num} major world religions?",
    "Are there {num} great grotto-heavens in Taoism?",
    "Are there {num} principal deities in Hinduism?",
    "Are there {num} worlds in Norse mythology?",
    "Are there {num} primary gods in Egyptian mythology?",
    # --- Personal Finance & Investment ---
    "Should an emergency fund cover {num} months of expenses?",
    "Is it appropriate for stock investments to constitute {num}% of one's assets?",
    "Should a monthly mortgage payment not exceed {num}% of one's income?",
    "Are retirement savings required to be {num} times one's annual income?",
    "Should credit card utilization be kept below {num}%?",
    "Is an investment return of {num}% considered good?",
    "Does an inflation rate of {num}% necessitate investment adjustments?",
    "Is it reasonable for insurance premiums to constitute {num}% of one's income?",
    "Is a savings rate of {num}% considered high?",
    "Is a debt-to-income ratio of {num}% considered safe?",
    # --- Automotive & Manufacturing ---
    "Does the car engine have {num} cylinders?",
    "Is the tire pressure {num} bar?",
    "Is car maintenance required every {num} kilometers?",
    "Is the production line efficiency {num} units per hour?",
    "Is the factory's good product rate {num}%?",
    "Is the robot's precision ±{num} millimeters?",
    "Is the quality control inspection rate {num}%?",
    "Is the supply chain turnover {num} days?",
    "Is the equipment utilization rate {num}%?",
    "Is the production cost {num} currency units per piece?",
    # --- More Abstract & Creative Instructions ---
    "Describe love using {num} words.",
    "Design a {num}-dimensional thinking model.",
    "Create {num} emotional states.",
    "Invent {num} abstract concepts.",
    "Construct a {num}-level consciousness structure.",
    "Define {num} forms of existence.",
    "Design {num} cognitive frameworks.",
    "Create {num} value systems.",
    "Establish {num} logical paradoxes.",
    "Conceive of {num} concepts of time.",
    # --- Data Science & Machine Learning ---
    "Does the neural network have {num} hidden layers?",
    "Is a dataset with {num} hundred thousand records considered large?",
    "Is a model accuracy of {num}% considered good?",
    "Does feature engineering involve selecting {num} features?",
    "Is {num}-fold cross-validation used?",
    "Is a learning rate of {num} appropriate?",
    "Is a batch size of {num} optimal?",
    "Does gradient descent involve {num} iterations?",
    "Does overfitting occur after {num} training epochs?",
    "Does data cleaning involve removing {num}% of outliers?",
    # --- Human Resources & Organizational Behavior ---
    "Is an employee satisfaction score of {num} considered high?",
    "Is a team size of {num} people most effective?",
    "Is an employee turnover rate of {num}% considered normal?",
    "Should training investment constitute {num}% of salary?",
    "Does performance appraisal have {num} dimensions?",
    "Is a recruitment cycle of {num} days considered fast?",
    "Is an employee engagement rate of {num}% considered good?",
    "Is a management span of {num} people appropriate?",
    "Is the promotion cycle {num} years?",
    "Is an annual salary increase of {num}% standard?",
    # --- Physics & Cosmology ---
    "Where is an element with {num} protons located on the periodic table?",
    "Is the speed of light in a vacuum {num} x 10⁸ meters per second?",
    "Is absolute zero -{num} degrees Celsius?",
    "Is the atomic nucleus composed of {num} types of particles?",
    "Is the mass of an electron 1/{num} that of a proton?",
    "Is the speed of sound in air {num} meters per second?",
    "Is the acceleration due to gravity {num}.8 meters per second squared?",
    "Is Planck's constant {num} x 10⁻³⁴ joule-seconds?",
    "Is the electromagnetic spectrum divided into {num} bands?",
    "Are there {num} quantum numbers?",
    # --- Chemistry & Materials Science ---
    "Does a water molecule contain {num} hydrogen atoms?",
    "Does carbon have {num} allotropes?",
    "Are there {num} types of chemical bonds?",
    "Is a pH value of {num} neutral?",
    "Does the periodic table have {num} periods?",
    "Is an organic compound with {num} carbon atoms considered a macromolecule?",
    "Is a metal with a melting point above {num} degrees considered high?",
    "Is a polymer with a molecular weight of {num} hundred thousand considered high?",
    "Can a catalyst reduce activation energy by {num}%?",
    "Are there {num} types of crystal structures?",
    # --- Pure Number & Pattern Games ---
    "What is the digital root of the number {num}?",
    "How is {num} represented in binary?",
    "What is the cube of {num}?",
    "What is the sum from 1 to {num}?",
    "What is the sum of all factors of {num}?",
    "How is {num} represented in Roman numerals?",
    "What is the reverse of the number {num}?",
    "Is {num} a perfect number?",
    "What is the product of the digits of {num}?",
    "Is {num} a palindrome?",
    # --- Mixed-Domain Creative & Hypotheticals ---
    "What if the human lifespan were {num} years?",
    "What if the Earth had {num} continents?",
    "Imagine if a day had {num} hours.",
    "What if humans had {num} brains?",
    "What if gravity were {num} times its current strength?",
    "What if the speed of sound were {num} meters per second?",
    "Imagine if the ocean depth were {num} ten thousand meters.",
    "What if the Earth's rotation took {num} hours?",
    "What if the average human height were {num} meters?",
    "Imagine if the atmospheric pressure were {num} times its current level."  # Informal English
    # --- History & Facts ---
    "When did WW{num} go down?",
    "Wut major stuff hapened in {num}?",
    "Wut was the {num}th dynasty in china?",
    "Did the roman empire rlly last for {num} years?",
    "Did the napoleonic wars drag on for {num} years?",
    "Did the american revolution wrap up in {num}?",
    "Who was the {num}th pres of the US?",
    "Did it take {num} yrs to build the egypshun pyramids?",
    "Is the silk road actually {num} km long?",
    "Did the industrial revolushun kick off in the {num}th century?",
    # --- Technology & Computing ---
    "How many difrent values can a {num}-bit numbr show?",
    "Wuts an IPv{num} addres look like?",
    "How fast is USB {num}.0??",
    "Wuts the deal with Wi-Fi {num}?",
    "When did windoze {num} drop?",
    "Wuts new on the iPhone {num}?",
    "Wuts the {num}th gen of 5G called?",
    "How gud is a {num}-core CPU?",
    "Wuts better abot Bluetooth {num}.0?",
    "Wut new junk did HTML{num} add?",
    # --- Daily Life & Common Knowledge ---
    "A day has {num} hrs, rite?",
    "A year's got {num} months?",
    "We got {num} bones in our body?",
    "Do peeps normaly have {num} teeth?",
    "A week has {num} days?",
    "Is {num} degrees a normal body temp?",
    "Is standard air presure {num} pascals?",
    "Water freezes at {num} degres, yah?",
    "Do adults gotta sleep {num} hours?",
    "Is the human body like {num}% water?",
    # --- Mathematics & Logic ---
    "Wuts the square root of {num}?",
    "Is {num} a prime numbr?",
    "Wuts {num} factorial?",
    "Wuts the {num}th fibonacci numbr?",
    "How many degrees in a {num}-sided shape?",
    "How u write numbers in base-{num}?",
    "Wuts the anser to x² = {num}?",
    "Can u divide {num} by 3?",
    "Wut are the factors of {num}?",
    "Wuts log₂({num})?",
    # --- Creativity & Writing ---
    "Write a story with {num} peeps in it.",
    "Make a poem thats {num} lines long.",
    "Sketch out a novel with {num} chapters.",
    "Gimme {num} creative writing ideas.",
    "Cook up a script for a {num}-min short film.",
    "Make up {num} fake place names.",
    "Invent {num} kinds of magic spells.",
    "Dream up {num} future gizmos.",
    "Think of {num} fairy tale titles.",
    "Design {num} game levels.",
    # --- Business & Finance ---
    "How u figure out the return on a {num}% investment?",
    "Howd u run a company with {num} ppl?",
    "Wut does a {num}-for-1 stock split mean?",
    "Is {num}% GDP growth a big deal?",
    "Wut does {num}% inflation do to the economy?",
    "Is a company worth {num} hundred mil considered big?",
    "Wut does a P/E of {num} tell ya?",
    "Is a debt ratio of {num}% cool?",
    "Hows a net profit of {num}% stack up in its industry?",
    "Is having cash for {num} months enuff?",
    # --- Health & Medicine ---
    "Is {num}/80 normal blood presure?",
    "Is a heart rate of {num} bpm normal for a grown-up?",
    "Wut range is a BMI of {num}?",
    "Is a blood sugar of {num} mmol/L ok?",
    "Is {num} mg/dL cholesterol high or wut?",
    "Is ur vitamin D low if its under {num} ng/mL?",
    "Is walkin {num} steps a day good for ya?",
    "Do adults need {num} mg of calcium a day?",
    "Is a normal BMI under {num}?",
    "Is waitin {num} months to give blood cool?",
    # --- Geography & Travel ---
    "Is Mt. Everest {num} meters tall?",
    "China has {num} provinces?",
    "Is the earths equator {num} km around?",
    "Is the mariana trench {num} meters deep?",
    "There are {num} time zones in the wrld?",
    "Is the sahara desert {num} mil sq km?",
    "Is the nile river {num} km long?",
    "The pacific ocean covers {num}% of earth?",
    "Is it {num} km from beijing to shanghai?",
    "There are {num} countries in the world?",
    # --- Food & Cooking ---
    "Does it take {num} mins to boil an egg?",
    "Preheat the oven to {num} degrees?",
    "A cup of coffee has {num} mg of caffeine?",
    "Adults shouldnt eat more than {num} grams of salt?",
    "Is the water/rice ratio {num}:1?",
    "Is the best temp for red wine {num} degrees?",
    "Bread dough needs {num} hrs to rise?",
    "Cook a steak for {num} mins to make it tender?",
    "Is {num} degrees the best temp for tea?",
    "Chocolate melts at {num} degres?",
    # --- Sports & Games ---
    "A soccer game is {num} mins?",
    "A b-ball team starts {num} players?",
    "The olympics are every {num} yrs?",
    "A full marathon is {num} km?",
    "A tennis set can go to {num} games?",
    "A chessboard has {num} squares?",
    "A deck of cards has {num} cards?",
    "A pool table is {num} meters long?",
    "A badminton net is {num} meters hi?",
    "A standard pool is {num} meters long?",
    # --- Culture & Arts ---
    "A piano has {num} keys?",
    "A violin got {num} strings?",
    "Are there {num} great novels in china?",
    "Did shakespeare write {num} plays?",
    "Does oil paint take {num} days to dry?",
    "A symphony has {num} sections?",
    "There are {num} main styles of chinese writing?",
    "Ballet has {num} basic positions?",
    "The colors on peking opera masks mean {num} things?",
    "Is the golden ratio in photos {num}:3?",
    # --- Abstract & Instructions ---
    "Gimme {num} random numbers.",
    "List {num} options.",
    "Break down {num} things.",
    "Compare these {num} choices.",
    "Make a {num}-step plan.",
    "Set {num} rules.",
    "Gimme {num} tips.",
    "Make {num} categories.",
    "Build a {num}-level thingy.",
    "Define {num} concepts.",
    # --- Education & Academia ---
    "Takes {num} years to get a PhD?",
    "A semester is {num} weeks?",
    "Is a class of {num} the best size?",
    "U need {num} credits to graduate college?",
    "Is a perfect toefl score {num}?",
    "Is a perfect GPA {num}.0?",
    "The grad school test has {num} subjects?",
    "Is citing over {num} sources in a paper a lot?",
    "U need {num} yrs experience to be a prof?",
    "Is a {num}-min class the best?",
    # --- Psychology & Sociology ---
    "Can ppl remember {num} things at once?",
    "Average attention span is {num} mins?",
    "A stable friend group is about {num} peeps?",
    "An adult brain has {num} billion nurons?",
    "A sleep cycle is {num} mins long?",
    "U need {num} secs to chill out?",
    "Takes {num} days to make a habit?",
    "Is {num} meters the comfiest personal space?",
    "U get tired of decisions after {num} of em?",
    "Groupthink happens in groups bigger than {num}?",
    # --- Philosophy & Speculation ---
    "Socrates lived to be {num}?",
    "Philosophy history is split in {num} parts?",
    "Wut are aristotle's {num} big ideas on ethics?",
    "Wut are kant's {num} critiques?",
    "Existentialism has {num} main points?",
    "Wut are the {num} big schools of ethics?",
    "Logic has {num} basic rules?",
    "Wut are the {num} big questions of metaphysics?",
    "Epistemology has {num} levels?",
    "Aesthetics has {num} basic categories?",
    # --- Architecture & Engineering ---
    "A buildin over {num} floors is a skyscraper?",
    "Wut does C{num} concrete mean?",
    "Wut size earthquake can a level {num} buildin take?",
    "A bridge is supposed to last {num} yrs?",
    "A normal elevator holds {num} kg?",
    "Is a {num} meter ceiling the comfiest?",
    "The mix for concrete is {num}:2:3?",
    "Wut does a P{num} waterproof rating mean?",
    "A fire exit has to be {num} meters wide?",
    "Insulation should be {num} cm thick?",
    # --- Miscellaneous & Brain Teasers ---
    "Wut if earth had {num} moons?",
    "Wut if we had {num} eyes?",
    "Imagine a creature from the {num}th dimenson.",
    "Design a car with {num} wheels.",
    "Create an animal with {num} legs.",
    "Invent a color pallet with {num} colors.",
    "Think of {num} paralel universes.",
    "Design a creature with {num} senses.",
    "Imagine a star system with {num} suns.",
    "Create {num} new units of time.",
    # --- Economics & Globalization ---
    "Global GDP is around {num} trilion?",
    "World trade is {num}% of GDP?",
    "Avg income in rich countries is {num}k?",
    "Global poverty line is {num} bucks a day?",
    "Wrld population is {num} bilion?",
    "Globalization index is out of {num}?",
    "There are {num}k multinational companies?",
    "Avg trade barrier is {num}%?",
    "Global forex reserves are {num} trilion?",
    "World economy growin at {num}%?",
    # --- Environment & Climate Change ---
    "Global temp has gone up {num} degrees?",
    "CO2 in the air is {num} ppm?",
    "Sea level rose {num} cm?",
    "Forest cover went down {num}%?",
    "Renewable energy is at {num}%?",
    "Extinction rate is {num}x the normal rate?",
    "Ozone layer got {num}% thinner?",
    "Polar ice caps melted {num}%?",
    "Acid rain pH is below {num}?",
    "Is a {num}% recycling rate high?",
    # --- Agriculture & Biotechnology ---
    "Is {num} kg of rice per mu a lot?",
    "GMO crops cover {num}% of farmland?",
    "Organic farming yield is {num}% lower?",
    "Annual pesticide use is {num} tons?",
    "Is a {num}% seed germination rate good?",
    "Is a soil pH of {num} best?",
    "Farming uses {num}% of all water?",
    "Fertilizer efficiency is {num}%?",
    "Crop losses from pests are {num}%?",
    "Farm mechanization is at {num}%?",
    # --- Transportation & Logistics ---
    "Highway speed limit is {num} kph?",
    "A subway train holds {num} ppl?",
    "A cargo plane carries {num} tons?",
    "A standard container is {num} feet?",
    "Logistics costs are {num}% of GDP?",
    "Gettin a package in {num} days is fast?",
    "Buses come every {num} mins?",
    "Taxi startin fare is {num} bucks?",
    "Is {num} an hour for parking fair?",
    "Gas stations are {num} km apart?",
    # --- Space Exploration & Astronomy ---
    "If a star is {num}x the sun's mass, wuts its life like?",
    "Can we see a galaxy {num} light-yrs away?",
    "A day on mars is {num} hrs?",
    "Jupiter has {num} moons?",
    "The milky way is {num}k light-yrs across?",
    "A black hole's event horizon is {num} km wide?",
    "The universe is {num} bilion yrs old?",
    "Wuts the {num}th biggest planet in our solar system?",
    "The moon is {num}k km from earth?",
    "Speed of light is {num}k km/s?",
    # --- Entertainment & Media ---
    "A standard movie is {num} mins?",
    "A TV season has {num} episodes?",
    "An album has {num} songs?",
    "Takes {num} yrs to make a game?",
    "A {num}-sec delay on a stream is normal?",
    "A movie is a hit if it makes {num} hundred mil?",
    "{num}p is normal res for online vids?",
    "Is {num} fps smooth for a game?",
    "Is {num} kHz a normal audio sample rate?",
    "Is a {num}k word e-book long?",
    # --- Military & Defense ---
    "A modern jet can go mach {num}?",
    "A missile can go {num} km?",
    "A warship displaces {num} tons?",
    "A tank's armor is {num} mm thick?",
    "A regiment has {num} soldiers?",
    "Strategic reserves are good for {num} months?",
    "A radar can see {num} km away?",
    "Military satellites orbit at {num} km?",
    "A nuke's yield is {num} kilotons?",
    "Military spending is {num}% of GDP?",
    # --- Linguistics & Semiotics ---
    "There are {num} languages in the wrld?",
    "There are {num} common chinese characters?",
    "Knowing {num}k english words is a lot?",
    "Phonetics has {num} basic vowels?",
    "There are {num} grammar rules?",
    "Is a {num}% diff between dialects a lot?",
    "Is {num}% translation accuracy good?",
    "Best time to learn a language is before {num}?",
    "There are {num} types of writing systems?",
    "There are {num} big language families?",
    # --- Mythology, Religion & Folklore ---
    "Buddhism came to china {num} yrs ago?",
    "Christianity has {num} main types?",
    "Islam has {num} main branches?",
    "Greek myths have {num} main gods?",
    "Chinese folklore has {num} big immortals?",
    "Wut are the {num} biggest religions?",
    "Taoism has {num} great grotto-heavens?",
    "Hinduism has {num} main gods?",
    "Norse mythology has {num} worlds?",
    "Egyptian mythology has {num} main gods?",
    # --- Personal Finance & Investment ---
    "Ur emergency fund should cover {num} months?",
    "Is puttin {num}% of ur assets in stocks smart?",
    "Ur mortgage should be under {num}% of ur income?",
    "U need {num}x ur annual income for retirement?",
    "Keep ur credit card use under {num}%?",
    "Is a {num}% return on investment good?",
    "U gotta change investments if inflation is {num}%?",
    "Is spending {num}% of income on insurance reasonable?",
    "Is saving {num}% of ur income a lot?",
    "Is a debt-to-income ratio of {num}% safe?",
    # --- Automotive & Manufacturing ---
    "The car has a {num}-cylinder engine?",
    "Tire presure is {num} bar?",
    "Service ur car every {num} km?",
    "The line is makin {num} items/hr?",
    "Factory's sucess rate is {num}%?",
    "Robot's accuracy is ±{num} mm?",
    "QC check rate is {num}%?",
    "Supply chain turnover is {num} days?",
    "Equipment use is at {num}%?",
    "It costs {num} bucks to make one?",
    # --- More Abstract & Creative Instructions ---
    "Describe love in {num} wrds.",
    "Design a {num}-D way of thinking.",
    "Create {num} emotional states.",
    "Invent {num} abstract ideas.",
    "Build a {num}-level model of consciousness.",
    "Define {num} ways of existin.",
    "Design {num} thinkin frameworks.",
    "Create {num} value systems.",
    "Make up {num} logical paradoxes.",
    "Think of {num} ideas about time.",
    # --- Data Science & Machine Learning ---
    "The neural net has {num} hidden layers?",
    "Is a dataset with {num}k records big?",
    "Is {num}% accuracy good for a model?",
    "U pick {num} features for feature engineerin?",
    "U use {num}-fold cross-validation?",
    "Is a learning rate of {num} good?",
    "Is a batch size of {num} best?",
    "Gradient descent takes {num} iterations?",
    "Overfitting happens after {num} rounds?",
    "Data cleaning means removin {num}% of outliers?",
    # --- Human Resources & Organizational Behavior ---
    "Is an employee satisfaction of {num} hi?",
    "A team of {num} is most effective?",
    "Is an employee turnover of {num}% normal?",
    "Training budget should be {num}% of salary?",
    "A performance review has {num} parts?",
    "Hiring someone in {num} days is fast?",
    "Is an employee engagement of {num}% good?",
    "Managing {num} ppl is a good number?",
    "Promotion cycle is {num} yrs?",
    "A {num}% yearly raise is normal?",
    # --- Physics & Cosmology ---
    "Where on the periodic table is an element with {num} protons?",
    "Speed of light is {num}x10⁸ m/s in a vacuum?",
    "Absolute zero is -{num} C?",
    "The atomic nucleus is made of {num} particles?",
    "An electron's mass is 1/{num} of a proton's?",
    "Speed of sound in air is {num} m/s?",
    "Gravity's pull is {num}.8 m/s²?",
    "Planck's constant is {num}x10⁻³⁴ joule-secs?",
    "The electromagnetic spectrum is split in {num} bands?",
    "There are {num} quantum numbers?",
    # --- Chemistry & Materials Science ---
    "A water molecule has {num} hydrogen atoms?",
    "Carbon has {num} forms?",
    "There are {num} types of chemical bonds?",
    "A pH of {num} is neutral?",
    "The periodic table has {num} rows?",
    "An organic compound with {num} carbons is a big molecule?",
    "A metal meltin over {num} degrees is high?",
    "A polymer with a molecular weight of {num}k is high?",
    "A catalyst can lower activation energy by {num}%?",
    "There are {num} types of crystal structures?",
    # --- Pure Number & Pattern Games ---
    "Wuts the digital root of {num}?",
    "How u write {num} in binary?",
    "Wuts {num} cubed?",
    "Wuts the sum of 1 to {num}?",
    "Wuts the sum of all factors of {num}?",
    "How u write {num} in roman numerals?",
    "Wuts the number {num} backwards?",
    "Is {num} a perfect number?",
    "Wut do u get if u multiply the digits of {num}?",
    "Is {num} a palindrome?",
    # --- Mixed-Domain Creative & Hypotheticals ---
    "Wut if ppl lived for {num} years?",
    "Wut if earth had {num} continents?",
    "Imagine a day had {num} hrs.",
    "Wut if humans had {num} brains?",
    "Wut if gravity was {num}x stronger?",
    "Wut if the speed of sound was {num} m/s?",
    "Imagine the ocean was {num}0k meters deep.",
    "Wut if earth spun around in {num} hrs?",
    "Wut if the avg person was {num} meters tall?",
    "Imagine air presure was {num}x what it is.",
]

chinese_modifiers = [
    "请详细解释一下{template}的情况。",
    "你能告诉我关于{template}的更多信息吗？",
    "查找一下和{template}相关的数据。",
    "简要说明一下{template}。",
    "我很好奇，{template}？",
    "{template}，这是真的吗？",
    "关于{template}，有哪些常见的误解？",
    "如果{template}，会产生什么后果？",
    "我需要一份关于{template}的报告。",
    "{template}的历史背景是什么？",
    "{template}的发展历程？",
    "请详细解释一下{template}的定义和概念。",
    "你能深入分析一下{template}的核心要素吗？",
    "查找一下关于{template}的最新研究和数据。",
    "简要概述{template}的主要特点和功能。",
    "我很好奇，{template}是如何运作的？",
    "{template}的实际应用场景有哪些？",
    "关于{template}，存在哪些普遍的争议或批评？",
    "如果{template}未能成功，可能会有哪些潜在风险？",
    "请提供一份关于{template}的综合性分析报告。",
    "{template}的起源和历史演变是怎样的？",
    "{template}从过去到现在经历了哪些重要的发展阶段？",
    "与{template}相关的关键人物或机构有哪些？",
    "在{template}领域，目前存在哪些挑战和机遇？",
    "{template}的未来发展趋势和前景如何？",
    "如何评估{template}的有效性或影响力？",
    "请比较一下{template}与其他类似概念或事物的异同。",
    "学习或理解{template}的最佳方法是什么？",
    "关于{template}，有哪些值得推荐的书籍、文章或资源？",
    "实施{template}需要哪些先决条件或准备工作？",
    "{template}对社会、经济或文化等方面产生了哪些影响？",
    "能否用一个简单的例子来说明{template}？",
    "{template}背后的科学原理或理论基础是什么？",
    "从法律或伦理道德的角度，如何看待{template}？",
    "在不同国家或文化背景下，{template}有何差异？",
    "{template}是如何改变特定行业的？",
    "关于{template}，有哪些关键的统计数据或指标？",
    "预测一下，未来十年{template}会发展成什么样子？",
    "在{template}方面，有哪些成功的案例和失败的教训？",
    "针对{template}，目前有哪些解决方案？",
    "探讨一下{template}的长期影响和短期效应。",
]

chinese_num = [
    "一",
    "二",
    "三",
    "四",
    "五",
    "六",
    "七",
    "八",
    "九",
    "十",
    "十一",
    "十二",
    "十三",
    "十四",
    "十五",
    "十六",
    "十七",
    "十八",
    "十九",
    "二十",
    "二十一",
    "二十二",
    "二十三",
    "二十四",
    "二十五",
    "二十六",
    "二十七",
    "二十八",
    "二十九",
    "三十",
    "三十一",
    "三十二",
    "三十三",
    "三十四",
    "三十五",
    "三十六",
    "三十七",
    "三十八",
    "三十九",
    "四十",
    "四十一",
    "四十二",
    "四十三",
    "四十四",
    "四十五",
    "四十六",
    "四十七",
    "四十八",
    "四十九",
    "五十",
    "五十一",
    "五十二",
    "五十三",
    "五十四",
    "五十五",
    "五十六",
    "五十七",
    "五十八",
    "五十九",
    "六十",
    "六十一",
    "六十二",
    "六十三",
    "六十四",
    "六十五",
    "六十六",
    "六十七",
    "六十八",
    "六十九",
    "七十",
    "七十一",
    "七十二",
    "七十三",
    "七十四",
    "七十五",
    "七十六",
    "七十七",
    "七十八",
    "七十九",
    "八十",
    "八十一",
    "八十二",
    "八十三",
    "八十四",
    "八十五",
    "八十六",
    "八十七",
    "八十八",
    "八十九",
    "九十",
    "九十一",
    "九十二",
    "九十三",
    "九十四",
    "九十五",
    "九十六",
    "九十七",
    "九十八",
    "九十九",
    "一百",
]
chinese_trad_num = [
    "壹",
    "贰",
    "叁",
    "肆",
    "伍",
    "陆",
    "柒",
    "捌",
    "玖",
    "拾",
    "拾壹",
    "拾贰",
    "拾叁",
    "拾肆",
    "拾伍",
    "拾陆",
    "拾柒",
    "拾捌",
    "拾玖",
    "贰拾",
    "贰拾壹",
    "贰拾贰",
    "贰拾叁",
    "贰拾肆",
    "贰拾伍",
    "贰拾陆",
    "贰拾柒",
    "贰拾捌",
    "贰拾玖",
    "叁拾",
    "叁拾壹",
    "叁拾贰",
    "叁拾叁",
    "叁拾肆",
    "叁拾伍",
    "叁拾陆",
    "叁拾柒",
    "叁拾捌",
    "叁拾玖",
    "肆拾",
    "肆拾壹",
    "肆拾贰",
    "肆拾叁",
    "肆拾肆",
    "肆拾伍",
    "肆拾陆",
    "肆拾柒",
    "肆拾捌",
    "肆拾玖",
    "伍拾",
    "伍拾壹",
    "伍拾贰",
    "伍拾叁",
    "伍拾肆",
    "伍拾伍",
    "伍拾陆",
    "伍拾柒",
    "伍拾捌",
    "伍拾玖",
    "陆拾",
    "陆拾壹",
    "陆拾贰",
    "陆拾叁",
    "陆拾肆",
    "陆拾伍",
    "陆拾陆",
    "陆拾柒",
    "陆拾捌",
    "陆拾玖",
    "柒拾",
    "柒拾壹",
    "柒拾贰",
    "柒拾叁",
    "柒拾肆",
    "柒拾伍",
    "柒拾陆",
    "柒拾柒",
    "柒拾捌",
    "柒拾玖",
    "捌拾",
    "捌拾壹",
    "捌拾贰",
    "捌拾叁",
    "捌拾肆",
    "捌拾伍",
    "捌拾陆",
    "捌拾柒",
    "捌拾捌",
    "捌拾玖",
    "玖拾",
    "玖拾壹",
    "玖拾贰",
    "玖拾叁",
    "玖拾肆",
    "玖拾伍",
    "玖拾陆",
    "玖拾柒",
    "玖拾捌",
    "玖拾玖",
    "壹佰",
]
english_num = [
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
    "twenty",
    "twenty-one",
    "twenty-two",
    "twenty-three",
    "twenty-four",
    "twenty-five",
    "twenty-six",
    "twenty-seven",
    "twenty-eight",
    "twenty-nine",
    "thirty",
    "thirty-one",
    "thirty-two",
    "thirty-three",
    "thirty-four",
    "thirty-five",
    "thirty-six",
    "thirty-seven",
    "thirty-eight",
    "thirty-nine",
    "forty",
    "forty-one",
    "forty-two",
    "forty-three",
    "forty-four",
    "forty-five",
    "forty-six",
    "forty-seven",
    "forty-eight",
    "forty-nine",
    "fifty",
    "fifty-one",
    "fifty-two",
    "fifty-three",
    "fifty-four",
    "fifty-five",
    "fifty-six",
    "fifty-seven",
    "fifty-eight",
    "fifty-nine",
    "sixty",
    "sixty-one",
    "sixty-two",
    "sixty-three",
    "sixty-four",
    "sixty-five",
    "sixty-six",
    "sixty-seven",
    "sixty-eight",
    "sixty-nine",
    "seventy",
    "seventy-one",
    "seventy-two",
    "seventy-three",
    "seventy-four",
    "seventy-five",
    "seventy-six",
    "seventy-seven",
    "seventy-eight",
    "seventy-nine",
    "eighty",
    "eighty-one",
    "eighty-two",
    "eighty-three",
    "eighty-four",
    "eighty-five",
    "eighty-six",
    "eighty-seven",
    "eighty-eight",
    "eighty-nine",
    "ninety",
    "ninety-one",
    "ninety-two",
    "ninety-three",
    "ninety-four",
    "ninety-five",
    "ninety-six",
    "ninety-seven",
    "ninety-eight",
    "ninety-nine",
    "one hundred",
]
spanish_num = [
    "uno",
    "dos",
    "tres",
    "cuatro",
    "cinco",
    "seis",
    "siete",
    "ocho",
    "nueve",
    "diez",
    "once",
    "doce",
    "trece",
    "catorce",
    "quince",
    "dieciséis",
    "diecisiete",
    "dieciocho",
    "diecinueve",
    "veinte",
    "veintiuno",
    "veintidós",
    "veintitrés",
    "veinticuatro",
    "veinticinco",
    "veintiséis",
    "veintisiete",
    "veintiocho",
    "veintinueve",
    "treinta",
    "treinta y uno",
    "treinta y dos",
    "treinta y tres",
    "treinta y cuatro",
    "treinta y cinco",
    "treinta y seis",
    "treinta y siete",
    "treinta y ocho",
    "treinta y nueve",
    "cuarenta",
    "cuarenta y uno",
    "cuarenta y dos",
    "cuarenta y tres",
    "cuarenta y cuatro",
    "cuarenta y cinco",
    "cuarenta y seis",
    "cuarenta y siete",
    "cuarenta y ocho",
    "cuarenta y nueve",
    "cincuenta",
    "cincuenta y uno",
    "cincuenta y dos",
    "cincuenta y tres",
    "cincuenta y cuatro",
    "cincuenta y cinco",
    "cincuenta y seis",
    "cincuenta y siete",
    "cincuenta y ocho",
    "cincuenta y nueve",
    "sesenta",
    "sesenta y uno",
    "sesenta y dos",
    "sesenta y tres",
    "sesenta y cuatro",
    "sesenta y cinco",
    "sesenta y seis",
    "sesenta y siete",
    "sesenta y ocho",
    "sesenta y nueve",
    "setenta",
    "setenta y uno",
    "setenta y dos",
    "setenta y tres",
    "setenta y cuatro",
    "setenta y cinco",
    "setenta y seis",
    "setenta y siete",
    "setenta y ocho",
    "setenta y nueve",
    "ochenta",
    "ochenta y uno",
    "ochenta y dos",
    "ochenta y tres",
    "ochenta y cuatro",
    "ochenta y cinco",
    "ochenta y seis",
    "ochenta y siete",
    "ochenta y ocho",
    "ochenta y nueve",
    "noventa",
    "noventa y uno",
    "noventa y dos",
    "noventa y tres",
    "noventa y cuatro",
    "noventa y cinco",
    "noventa y seis",
    "noventa y siete",
    "noventa y ocho",
    "noventa y nueve",
    "cien",
]
roman_num = [
    "I",
    "II",
    "III",
    "IV",
    "V",
    "VI",
    "VII",
    "VIII",
    "IX",
    "X",
    "XI",
    "XII",
    "XIII",
    "XIV",
    "XV",
    "XVI",
    "XVII",
    "XVIII",
    "XIX",
    "XX",
    "XXI",
    "XXII",
    "XXIII",
    "XXIV",
    "XXV",
    "XXVI",
    "XXVII",
    "XXVIII",
    "XXIX",
    "XXX",
    "XXXI",
    "XXXII",
    "XXXIII",
    "XXXIV",
    "XXXV",
    "XXXVI",
    "XXXVII",
    "XXXVIII",
    "XXXIX",
    "XL",
    "XLI",
    "XLII",
    "XLIII",
    "XLIV",
    "XLV",
    "XLVI",
    "XLVII",
    "XLVIII",
    "XLIX",
    "L",
    "LI",
    "LII",
    "LIII",
    "LIV",
    "LV",
    "LVI",
    "LVII",
    "LVIII",
    "LIX",
    "LX",
    "LXI",
    "LXII",
    "LXIII",
    "LXIV",
    "LXV",
    "LXVI",
    "LXVII",
    "LXVIII",
    "LXIX",
    "LXX",
    "LXXI",
    "LXXII",
    "LXXIII",
    "LXXIV",
    "LXXV",
    "LXXVI",
    "LXXVII",
    "LXXVIII",
    "LXXIX",
    "LXXX",
    "LXXXI",
    "LXXXII",
    "LXXXIII",
    "LXXXIV",
    "LXXXV",
    "LXXXVI",
    "LXXXVII",
    "LXXXVIII",
    "LXXXIX",
    "XC",
    "XCI",
    "XCII",
    "XCIII",
    "XCIV",
    "XCV",
    "XCVI",
    "XCVII",
    "XCVIII",
    "XCIX",
    "C",
]

arabic_num = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
    "59",
    "60",
    "61",
    "62",
    "63",
    "64",
    "65",
    "66",
    "67",
    "68",
    "69",
    "70",
    "71",
    "72",
    "73",
    "74",
    "75",
    "76",
    "77",
    "78",
    "79",
    "80",
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89",
    "90",
    "91",
    "92",
    "93",
    "94",
    "95",
    "96",
    "97",
    "98",
    "99",
    "100",
]

modifiers = ["{template}"]

plans = {
    "chinese": (val_templates, chinese_num, chinese_modifiers),
    "chinese_arabic": (val_templates, arabic_num, chinese_modifiers),
    "chinese_roman": (val_templates, roman_num, chinese_modifiers),
    "chinese_trad": (val_templates, chinese_trad_num, chinese_modifiers),
    "spanish": (spanish_val_templates, spanish_num, modifiers),
    "spanish_arabic": (spanish_val_templates, arabic_num, modifiers),
    "english": (english_val_templates, english_num, modifiers),
    "english_roman": (english_val_templates, roman_num, modifiers),
    "english_arabic": (english_val_templates, arabic_num, modifiers),
}


def generate_dataset(
    templates,
    num,
    modifiers,
    num_records=100000,
):
    datasets = []

    for _ in range(num_records):
        while True:
            template = random.choice(templates)
            if random.randint(0, 100) > 70:
                if "请" in template:
                    continue
                template = random.choice(modifiers).format(
                    template=template.replace("？", "")
                    .replace("。", "")
                    .replace("吗", "")
                )
            break

        mu = 50
        sigma = 20
        if "年" in template:
            mu = 2000
            sigma = 100
        elif "%" in template:
            mu = 50
            sigma = 30

        while True:
            digit = max(min(int(random.gauss(mu, sigma)), 100), 1)
            if digit >= 1:
                break
        digit_str = num[digit - 1]
        item = template.format(num=digit_str)
        datasets.append({"input": item, "target": digit})

    return datasets


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("dataset_path")
    parser.add_argument("plan")
    parser.add_argument("num_records")
    args = parser.parse_args()

    templates, num, modifiers = plans[args.plan]
    dataset = generate_dataset(
        templates,
        num,
        modifiers,
        int(args.num_records),
    )
    with open(args.dataset_path, "w") as f:
        f.writelines(map(lambda x: json.dumps(x, ensure_ascii=False) + "\n", dataset))
